"""Authoritative typing contract for the core PyO3 extension surface.

The declarations in this file are maintained with the registrations in
``crates/kwavers-python/src/lib.rs`` and the core binding implementations.
They intentionally cover the stable simulation contract rather than expose
untyped implementation details from the extension.
"""

from typing import List, Optional, Sequence, Tuple, Union

import numpy as np
from numpy.typing import NDArray

Float64Array = NDArray[np.float64]
BoolArray = NDArray[np.bool_]
Signal = Float64Array


class Grid:
    def __init__(self, nx: int, ny: int, nz: int, dx: float, dy: float, dz: float) -> None: ...
    @property
    def nx(self) -> int: ...
    @property
    def ny(self) -> int: ...
    @property
    def nz(self) -> int: ...
    @property
    def dx(self) -> float: ...
    @property
    def dy(self) -> float: ...
    @property
    def dz(self) -> float: ...
    @property
    def lx(self) -> float: ...
    @property
    def ly(self) -> float: ...
    @property
    def lz(self) -> float: ...
    def total_points(self) -> int: ...
    def dimensions(self) -> Tuple[int, int, int]: ...
    def spacing(self) -> Tuple[float, float, float]: ...


class Medium:
    def __init__(
        self,
        sound_speed: Float64Array,
        density: Float64Array,
        absorption: Optional[Float64Array] = None,
        alpha_power: Optional[Union[float, Float64Array]] = None,
        nonlinearity: Optional[Float64Array] = None,
    ) -> None: ...
    @staticmethod
    def homogeneous(
        sound_speed: float,
        density: float,
        absorption: float = 0.0,
        nonlinearity: float = 0.0,
        alpha_power: float = 1.0,
        grid: Optional[Grid] = None,
    ) -> "Medium": ...
    @staticmethod
    def elastic(
        c_compression: float,
        c_shear: float,
        density: float,
        grid: Optional[Grid] = None,
    ) -> "Medium": ...
    @staticmethod
    def elastic_heterogeneous(
        c_compression: Float64Array,
        c_shear: Float64Array,
        density: Float64Array,
        reference_frequency: float = 1.0e6,
    ) -> "Medium": ...
    @property
    def is_homogeneous(self) -> bool: ...
    @property
    def sound_speed(self) -> float: ...


class Source:
    @staticmethod
    def plane_wave(
        grid: Grid,
        frequency: float,
        amplitude: float,
        direction: Optional[Tuple[float, float, float]] = None,
    ) -> "Source": ...
    @staticmethod
    def point(
        position: Tuple[float, float, float],
        frequency: float,
        amplitude: float,
    ) -> "Source": ...
    @staticmethod
    def from_mask(
        mask: Float64Array,
        signal: Signal,
        frequency: float,
        mode: Optional[str] = None,
    ) -> "Source": ...
    @staticmethod
    def from_initial_pressure(p0: Union[Float64Array, NDArray[np.float64]]) -> "Source": ...
    @property
    def source_type(self) -> str: ...
    @property
    def amplitude(self) -> float: ...


class Sensor:
    @staticmethod
    def point(position: Tuple[float, float, float]) -> "Sensor": ...
    @staticmethod
    def from_mask(mask: BoolArray) -> "Sensor": ...
    @staticmethod
    def grid() -> "Sensor": ...
    def set_record(self, modes: Sequence[str]) -> None: ...
    @property
    def record(self) -> List[str]: ...
    def set_record_start_index(self, index: int) -> None: ...
    @property
    def record_start_index(self) -> int: ...
    @property
    def num_sensors(self) -> int: ...
    @property
    def sensor_type(self) -> str: ...


class SolverType:
    FDTD: "SolverType"
    PSTD: "SolverType"
    Hybrid: "SolverType"
    PstdGpu: "SolverType"
    Elastic: "SolverType"
    ElasticPSTD: "SolverType"
    Helmholtz: "SolverType"
    BEM: "SolverType"
    DG: "SolverType"
    Nonlinear: "SolverType"
    Poroelastic: "SolverType"
    RayleighSommerfeld: "SolverType"


class PmlConfig:
    def __init__(self) -> None: ...


class HelmholtzConfig:
    def __init__(self) -> None: ...


class NonlinearConfig:
    def __init__(self) -> None: ...


class ThermalConfig:
    def __init__(self, center_frequency: float) -> None: ...


class SimulationResult:
    @property
    def sensor_data(self) -> Float64Array: ...
    @property
    def time(self) -> Float64Array: ...
    @property
    def shape(self) -> Tuple[int, int, int]: ...
    @property
    def sensor_data_shape(self) -> Tuple[int, int]: ...
    @property
    def time_steps(self) -> int: ...
    @property
    def dt(self) -> float: ...
    @property
    def final_time(self) -> float: ...
    @property
    def num_sensors(self) -> int: ...
    @property
    def p_max(self) -> Optional[Float64Array]: ...
    @property
    def p_min(self) -> Optional[Float64Array]: ...
    @property
    def p_rms(self) -> Optional[Float64Array]: ...
    @property
    def p_final(self) -> Optional[Float64Array]: ...
    @property
    def p_max_field(self) -> Optional[Float64Array]: ...
    @property
    def p_min_field(self) -> Optional[Float64Array]: ...
    @property
    def p_rms_field(self) -> Optional[Float64Array]: ...
    @property
    def p_final_field(self) -> Optional[Float64Array]: ...
    @property
    def thermal_temperature(self) -> Optional[Float64Array]: ...
    @property
    def thermal_dose(self) -> Optional[Float64Array]: ...


class Simulation:
    def __init__(
        self,
        grid: Grid,
        medium: Medium,
        source: Source,
        sensor: Sensor,
        solver: Optional[SolverType] = None,
        pml_size: Optional[int] = None,
    ) -> None: ...
    def set_pml_size(self, size: int) -> None: ...
    def set_kspace_correction(self, mode: str) -> None: ...
    @property
    def kspace_correction(self) -> str: ...
    def set_compatibility_mode(self, mode: str) -> None: ...
    @property
    def compatibility_mode(self) -> str: ...
    @property
    def pml_size(self) -> Optional[int]: ...
    def set_pml_size_xyz(self, x: int, y: int, z: int) -> None: ...
    def set_pml_alpha(self, alpha: float) -> None: ...
    def set_pml_alpha_xyz(self, ax: float, ay: float, az: float) -> None: ...
    def set_pml_inside(self, inside: bool) -> None: ...
    @property
    def pml_inside(self) -> bool: ...
    def set_nonlinear(self, enable: bool) -> None: ...
    @property
    def nonlinear(self) -> bool: ...
    def set_axisymmetric(self, enable: bool) -> None: ...
    @property
    def axisymmetric(self) -> bool: ...
    def set_alpha_coeff(self, alpha: float) -> None: ...
    def set_alpha_power(self, power: float) -> None: ...
    @property
    def alpha_coeff(self) -> float: ...
    @property
    def alpha_power(self) -> float: ...
    def set_helmholtz_wavenumber(self, frequency: float) -> None: ...
    @property
    def helmholtz_frequency(self) -> Optional[float]: ...
    def clear_thermal(self) -> None: ...
    @property
    def has_thermal(self) -> bool: ...
    def clear_poroelastic(self) -> None: ...
    @property
    def has_poroelastic(self) -> bool: ...
    def run(
        self,
        time_steps: int,
        dt: Optional[float] = None,
        record_start_index: int = 1,
        record_modes: Optional[Sequence[str]] = None,
    ) -> SimulationResult: ...
