//! Forward FDTD model construction and execution.

use super::{geometry::FwiGeometry, FwiProcessor, RHO_SEISMIC_REF};
use crate::core::error::{KwaversError, KwaversResult, ValidationError};
use crate::domain::boundary::cpml::{CPMLConfig, PerDimensionPML};
use crate::domain::grid::Grid;
use crate::domain::medium::heterogeneous::HeterogeneousFactory;
use ndarray::{s, Array2, Array3, Array4};

impl FwiProcessor {
    /// Generate receiver-time synthetic data for a model and acquisition geometry.
    ///
    /// # Theorem
    ///
    /// Returns the discrete forward map
    /// `F_h(c; G) = R_G p_h(c, q_G)`
    /// using the same FDTD state history as [`Self::invert`].  Any synthetic
    /// data used by examples, tests, or callers is generated by the same
    /// discrete operator as the FWI objective and gradient.
    /// # Errors
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub fn generate_synthetic_data(
        &self,
        model: &Array3<f64>,
        geometry: &FwiGeometry,
        grid: &Grid,
    ) -> KwaversResult<Array2<f64>> {
        geometry.validate(grid, self.parameters.nt)?;
        self.forward_model_sensor_only(model, geometry, grid)
    }

    /// Construct a configured, CPML-enabled FDTD solver ready for time-stepping.
    ///
    /// ## Single source of truth
    ///
    /// Both `forward_model` (full history) and `forward_model_sensor_only` (no
    /// history) require identical solver setup.  This helper centralises that
    /// setup so neither variant drifts from the other.
    ///
    /// ## Returns
    /// `(solver, (nx, ny, nz), dt)` at t = 0 ready for `step_forward` calls.
    /// # Errors
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub(super) fn build_fdtd_solver_for_forward(
        &self,
        model: &Array3<f64>,
        geometry: &FwiGeometry,
        grid: &Grid,
    ) -> KwaversResult<(crate::solver::fdtd::FdtdSolver, (usize, usize, usize), f64)> {
        use crate::solver::fdtd::{FdtdConfig, FdtdSolver, KSpaceCorrectionMode};

        geometry.validate(grid, self.parameters.nt)?;
        let dt = self.validate_time_step(model, grid)?;
        let num_steps = self.parameters.nt;

        let config = FdtdConfig {
            spatial_order: 2,
            staggered_grid: true,
            cfl_factor: 0.3,
            subgridding: false,
            subgrid_factor: 2,
            enable_gpu_acceleration: false,
            enable_nonlinear: false,
            kspace_correction: KSpaceCorrectionMode::None,
            nt: num_steps,
            dt,
            sensor_mask: Some(geometry.sensor_mask.clone()),
            geometry: Default::default(),
        };

        let (nx, ny, nz) = grid.dimensions();
        let density = Array3::from_elem((nx, ny, nz), RHO_SEISMIC_REF);
        let medium = HeterogeneousFactory::from_arrays(
            model.clone(),
            density,
            None,
            None, // alpha_power: default 1.0
            None,
            self.parameters.frequency,
        )
        .map_err(crate::core::error::KwaversError::InvalidInput)?;

        let mut solver = FdtdSolver::new(config, grid, &medium, geometry.source.clone())?;

        // Enable CPML absorbing boundaries.
        // Theorem (CPML optimal thickness): σ_max = -(m+1)·ln(R_target) / (2·d·η)
        // Reference: Roden & Gedney (2000), Microwave Opt. Technol. Lett. 27(5), 334-338.
        let c_max = model.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        let y_pml = if ny > 20 { 10usize } else { 0usize };
        let cpml_config = CPMLConfig {
            thickness: 10,
            per_dimension: PerDimensionPML::new(10, y_pml, 10),
            ..CPMLConfig::default()
        };
        solver.enable_cpml(cpml_config, dt, c_max)?;

        Ok((solver, (nx, ny, nz), dt))
    }

    /// Run the forward FDTD model and return both receiver traces and the full
    /// pressure-history volume needed by the adjoint pass.
    ///
    /// ## Memory contract
    ///
    /// Allocates `Array4<f64>` of shape `(nt, nx, ny, nz)` (≈ 3.3 GB for
    /// nt=2115, 64×48×64).  Do not call from `compute_objective` or any
    /// line-search path; use `forward_model_sensor_only` there.
    /// # Errors
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub(super) fn forward_model(
        &self,
        model: &Array3<f64>,
        geometry: &FwiGeometry,
        grid: &Grid,
    ) -> KwaversResult<(Array2<f64>, Array4<f64>)> {
        let (mut solver, (nx, ny, nz), _dt) =
            self.build_fdtd_solver_for_forward(model, geometry, grid)?;

        let mut history = Array4::zeros((self.parameters.nt, nx, ny, nz));

        for t in 0..self.parameters.nt {
            solver.step_forward()?;
            history
                .slice_mut(s![t, .., .., ..])
                .assign(&solver.fields.p);
        }

        let recorded = solver
            .sensor_recorder
            .extract_pressure_data()
            .ok_or_else(|| {
                KwaversError::Validation(ValidationError::ConstraintViolation {
                    message: "FWI forward model requires at least one receiver".to_owned(),
                })
            })?;
        let synthetic = recorded.slice(s![.., 0..self.parameters.nt]).to_owned();

        Ok((synthetic, history))
    }

    /// Run the forward FDTD model and return only receiver traces — no history.
    ///
    /// ## Theorem
    ///
    /// The L2 objective depends only on `d_syn(r,t)`, not on `p(x,t)`.  Storing
    /// `p(x,t)` is unnecessary for objective evaluation and prohibits safe
    /// shot-level parallelism in the line search.
    ///
    /// ## Memory contract
    ///
    /// Peak allocation per call: O(N_receivers × nt × 8 bytes) ≈ 5 MB.  Total
    /// per-call footprint ~55 MB; safe to run in parallel via `rayon::par_iter`.
    /// # Errors
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub(super) fn forward_model_sensor_only(
        &self,
        model: &Array3<f64>,
        geometry: &FwiGeometry,
        grid: &Grid,
    ) -> KwaversResult<Array2<f64>> {
        let (mut solver, _dims, _dt) = self.build_fdtd_solver_for_forward(model, geometry, grid)?;

        for _ in 0..self.parameters.nt {
            solver.step_forward()?;
        }

        let recorded = solver
            .sensor_recorder
            .extract_pressure_data()
            .ok_or_else(|| {
                KwaversError::Validation(ValidationError::ConstraintViolation {
                    message: "FWI forward model requires at least one receiver".to_owned(),
                })
            })?;
        let synthetic = recorded.slice(s![.., 0..self.parameters.nt]).to_owned();

        Ok(synthetic)
    }
}
