[simulation]
domain_size_x = 0.06
domain_size_yz = 0.04
points_per_wavelength = 6
frequency = 1000000.0  # 1 MHz - typical HIFU frequency
# amplitude is now part of [source]
num_cycles = 5.0
pml_thickness = 10
pml_sigma_acoustic = 100.0
pml_sigma_light = 10.0
pml_polynomial_order = 2
pml_reflection = 0.000001
kspace_alpha = 0.5     # k-space correction coefficient

[source]
# HIFU transducer parameters
num_elements = 32
signal_type = "sine"
frequency = 1000000.0  # Source signal frequency
amplitude = 1.0e6      # Source signal amplitude
focus_x = 0.03
focus_y = 0.0
focus_z = 0.0
# phase is optional

[output]
pressure_file = "hifu_pressure.csv"
light_file = "hifu_light.csv"
summary_file = "hifu_summary.csv"
snapshot_interval = 10
enable_visualization = true