
        domain_size_x = 0.05
        domain_size_yz = 0.03
        points_per_wavelength = 6
        frequency = 180000.0
        amplitude = 1.0e5
        num_cycles = 2.0
        pml_thickness = 5
        pml_sigma_acoustic = 100.0
        pml_sigma_light = 10.0
        pml_polynomial_order = 2
        pml_reflection = 0.000001

        num_elements = 4
        signal_type = "sine"
        focus_x = 0.025
        focus_y = 0.0
        focus_z = 0.015

        snapshot_interval = 10
        light_file = "sdt_light_output.csv"
    