//! HAS solver with operator splitting.
//!
//! ## Algorithm — Strang Splitting (Strang 1968)
//!
//! For each propagation step Δz the pressure field is advanced by:
//!
//! ```text
//! p_{n+1} = D(Δz/2) · N(Δz) · A(Δz) · D(Δz/2)  [p_n]
//! ```
//!
//! where:
//! - D = diffraction operator (FFT-based angular spectrum, Goodman 2005)
//! - N = nonlinearity operator (Burgers equation, Hamilton & Blackstock 2008)
//! - A = absorption operator (power-law exponential decay, Szabo 1994)
//!
//! ## Theorem (2nd-order Strang splitting accuracy)
//!
//! **Statement.** Let L = D + N + A be the full generator and let each operator
//! exponential U_X(s) denote the exact solution of `∂p/∂z = X[p]` for pseudo-time s.
//! The Strang-split approximation
//!
//! ```text
//! S(Δz) = U_D(Δz/2) · U_{N+A}(Δz) · U_D(Δz/2)
//! ```
//!
//! satisfies `||U_L(Δz) − S(Δz)|| = O(Δz³)` per step (global error O(Δz²)).
//!
//! **Proof sketch.** Baker-Campbell-Hausdorff expansion of `S(Δz)` gives:
//!
//! ```text
//! S(Δz) = exp(Δz·(D + N + A) + Δz³/24 · [D,[D, N+A]] + O(Δz⁴))
//! ```
//!
//! The leading error term is O(Δz³) per step, proving 2nd-order accuracy.
//! The commutator `[D, D] = 0` eliminates the O(Δz²) Baker-Campbell-Hausdorff
//! term that is present in the asymmetric Lie-Trotter splitting
//! `U_D(Δz) · U_{N+A}(Δz)`. (Strang 1968, Thm. 2.)
//!
//! ## Theorem (N-before-A operator order)
//!
//! **Statement.** In the inner pair `U_{N+A}(Δz) ≈ U_N(Δz) · U_A(Δz)`, the
//! Lie-Trotter split places N before A. The reverse order A·N introduces a
//! systematic error of O(Δz²·\[A,N\]) per step.
//!
//! **Physical justification.** The commutator `[A, N]` is non-zero when
//! absorption α is frequency-dependent (as in power-law models `α ∝ f^y`).
//! Applying A before N damps the harmonics generated by N at the current step
//! before they are computed — a causality violation in the operator sequence
//! that underestimates second-harmonic amplitudes by O(α·β·Δz).
//!
//! Physically: nonlinear distortion (N) generates new frequency content during
//! propagation; absorption (A) then removes it according to the spectrum of the
//! distorted wave. Reversing this order would apply absorption to the undistorted
//! spectrum, underestimating power-law damping of high harmonics.
//!
//! Reference: Zemp RJ et al. (2003). J. Acoust. Soc. Am. 113(1), 139–152,
//! §II.B eq. (10) and surrounding discussion of operator ordering.
//!
//! ## References
//!
//! - Strang G (1968). "On the construction and comparison of difference schemes."
//!   SIAM J. Numer. Anal. 5(3), 506–517. DOI: 10.1137/0705041
//! - Goodman JW (2005). Introduction to Fourier Optics. Roberts & Co., §3.
//! - Hamilton MF, Blackstock DT (2008). Nonlinear Acoustics. ASA Press.
//! - Szabo TL (1994). J. Acoust. Soc. Am. 96(1), 491–500. DOI: 10.1121/1.410434
//! - Zemp RJ et al. (2003). J. Acoust. Soc. Am. 113(1), 139–152.
//!   DOI: 10.1121/1.1528928

#[cfg(test)]
mod tests;

use kwavers_core::error::KwaversResult;
use kwavers_grid::Grid;
use leto::Array3;

use super::{
    HASConfig, HasAbsorptionOperator, HybridAsDiffractionOperator, HybridAsNonlinearOperator,
};

/// Hybrid Angular Spectrum solver with Strang operator splitting.
#[derive(Debug)]
pub struct HybridAngularSpectrumSolver {
    diffraction: HybridAsDiffractionOperator,
    nonlinearity: HybridAsNonlinearOperator,
    absorption: HasAbsorptionOperator,
}

impl HybridAngularSpectrumSolver {
    /// Construct from grid and configuration.
    /// # Errors
    /// - Propagates any [`crate::KwaversError`] returned by called functions.
    ///
    pub fn new(grid: &Grid, config: &HASConfig) -> KwaversResult<Self> {
        let diffraction = HybridAsDiffractionOperator::new(grid, config)?;
        let nonlinearity = HybridAsNonlinearOperator::new(config);
        let absorption = HasAbsorptionOperator::new(config)?;

        Ok(Self {
            diffraction,
            nonlinearity,
            absorption,
        })
    }

    /// Propagate pressure field for `num_steps` steps of size `dz`.
    ///
    /// ## Algorithm (Strang 1968, Zemp et al. 2003)
    ///
    /// Each step applies the Strang-split operators in the order:
    ///
    /// ```text
    /// p_{n+1} = D(Δz/2) · N(Δz) · A(Δz) · D(Δz/2)  [p_n]
    /// ```
    ///
    /// The half-steps in D bracket the full nonlinear and absorption steps,
    /// yielding 2nd-order accuracy in Δz (Strang 1968).
    ///
    /// ## Parameters
    /// - `initial`   — initial pressure field `p[ix, iy, iz]` (Pa)
    /// - `num_steps` — number of Δz steps to advance
    /// - `dz`        — axial step size (m)
    ///
    /// ## References
    /// - Strang G (1968). SIAM J. Numer. Anal. 5(3), 506–517.
    ///   DOI: 10.1137/0705041
    /// - Zemp RJ et al. (2003). J. Acoust. Soc. Am. 113(1), 139–152.
    ///   DOI: 10.1121/1.1528928
    /// # Errors
    /// - Propagates any [`crate::KwaversError`] returned by called functions.
    ///
    pub fn propagate_steps(
        &self,
        initial: &Array3<f64>,
        num_steps: usize,
        dz: f64,
    ) -> KwaversResult<Array3<f64>> {
        let mut pressure = initial.clone();

        for _step in 0..num_steps {
            // Strang splitting for 2nd order accuracy
            pressure = self.diffraction.apply(&pressure, dz / 2.0)?;
            pressure = self.nonlinearity.apply(&pressure, dz)?;
            pressure = self.absorption.apply(&pressure, dz)?;
            pressure = self.diffraction.apply(&pressure, dz / 2.0)?;
        }

        Ok(pressure)
    }
}
