"""CT-derived finite-frequency abdominal FWI.

The model is a deterministic 2-D slice inversion used for feasibility
analysis on the existing kidney and liver CT histotripsy examples. Baseline
targeting uses a single-scattering finite-frequency Born map from sound-speed
contrast to pitch-catch encoded measurements. Nonlinear source maps are
generated by the co-located bounded Westervelt and Rayleigh-Plesset simulation
module, then inverted through reduced receiver operators so the remaining model
limits stay explicit.
"""

from __future__ import annotations

from dataclasses import dataclass
import numpy as np
from scipy import ndimage

from abdominal_fwi.constants import C_REF_M_S
from abdominal_fwi.metrics import (
    contrast_to_noise,
    equal_volume_dice,
    metric_block,
)
from abdominal_fwi.operators import (
    build_fundamental_matrix,
    build_nonlinear_matrix,
    build_subharmonic_matrix,
)
from abdominal_fwi.regularization import active_degree, laplacian_apply
from abdominal_fwi.simulation import SimulationChannels, simulate_westervelt_channels


@dataclass(frozen=True)
class PreparedSlice:
    """CT, segmentation, and acoustic maps on one inversion slice."""

    name: str
    title: str
    ct_hu: np.ndarray
    sound_speed_m_s: np.ndarray
    label: np.ndarray
    imaging_mask: np.ndarray
    organ_mask: np.ndarray
    target_mask: np.ndarray
    spacing_m: float
    source_index: int


@dataclass(frozen=True)
class ApertureConfig:
    """Acquisition and inversion constants for the abdominal FWI slice."""

    element_count: int = 256
    imaging_receiver_count: int = 64
    imaging_receiver_samples: int = 6
    frequencies_hz: tuple[float, ...] = (
        150_000.0,
        250_000.0,
        350_000.0,
        500_000.0,
        750_000.0,
    )
    receiver_offsets: tuple[int, ...] = (32, 48, 64, 96, 128, 160)
    radius_margin_m: float = 0.035
    therapy_focal_radius_m: float = 0.142
    therapy_lateral_extent_m: float = 0.230
    therapy_central_cutout_m: float = 0.040
    iterations: int = 18
    regularization: float = 2.5e-3
    smoothness_regularization: float = 1.2e-1
    lesion_delta_c_m_s: float = -35.0
    westervelt_frequency_hz: float = 750_000.0
    westervelt_source_pressure_pa: float = 2.0e6
    westervelt_source_gain: float = 1.0
    westervelt_cycles: float = 6.0
    westervelt_cfl: float = 0.18
    westervelt_pml_cells: int = 6
    bubble_radius_m: float = 8.0e-6
    bubble_drive_gain: float = 0.8
    bubble_substeps: int = 8
    bubble_max_radius_ratio: float = 8.0
    bubble_wall_speed_limit_m_s: float = 1200.0


@dataclass(frozen=True)
class InversionResult:
    """Full-grid reconstruction arrays and scalar diagnostics."""

    target_map: np.ndarray
    reconstruction_map: np.ndarray
    error_map: np.ndarray
    metrics: dict[str, float | int | list[float]]


@dataclass(frozen=True)
class CaseResult:
    """Targeting and lesion-state FWI outputs for one prepared CT slice."""

    prepared: PreparedSlice
    lesion_mask: np.ndarray
    simulation: SimulationChannels
    targeting: InversionResult
    lesioning: InversionResult
    subharmonic: InversionResult
    nonlinear: InversionResult


def run_case(prepared: PreparedSlice, config: ApertureConfig) -> CaseResult:
    """Run CT-derived targeting FWI and lesion-state time-lapse FWI."""

    active_mask = prepared.imaging_mask
    matrix = build_fundamental_matrix(prepared, active_mask, config)

    targeting = reconstruct_targeting(prepared, active_mask, matrix, config)
    lesion_mask = lesion_core(prepared.target_mask)
    simulation = simulate_westervelt_channels(prepared, lesion_mask, config)
    lesioning = reconstruct_lesioning(
        prepared,
        active_mask,
        matrix,
        lesion_mask,
        config,
    )
    del matrix

    subharmonic_matrix = build_subharmonic_matrix(prepared, active_mask, config)
    subharmonic = reconstruct_subharmonic(
        prepared,
        active_mask,
        subharmonic_matrix,
        simulation,
        config,
    )
    del subharmonic_matrix

    nonlinear_matrix = build_nonlinear_matrix(prepared, active_mask, config)
    nonlinear = reconstruct_nonlinear(
        prepared,
        active_mask,
        nonlinear_matrix,
        simulation,
        config,
    )

    return CaseResult(
        prepared=prepared,
        lesion_mask=lesion_mask,
        simulation=simulation,
        targeting=targeting,
        lesioning=lesioning,
        subharmonic=subharmonic,
        nonlinear=nonlinear,
    )


def reconstruct_targeting(
    prepared: PreparedSlice,
    active_mask: np.ndarray,
    matrix: np.ndarray,
    config: ApertureConfig,
) -> InversionResult:
    """Reconstruct baseline CT-derived sound-speed contrast for targeting."""

    reference_c = float(np.median(prepared.sound_speed_m_s[active_mask]))
    target = np.zeros(prepared.sound_speed_m_s.shape, dtype=np.float32)
    target[active_mask] = (
        (prepared.sound_speed_m_s[active_mask] - reference_c) / C_REF_M_S
    )
    reconstruction, metrics = solve_contrast(matrix, target[active_mask], active_mask, config)

    full_recon = np.zeros_like(target)
    full_recon[active_mask] = reconstruction
    error = np.zeros_like(target)
    error[active_mask] = full_recon[active_mask] - target[active_mask]
    metrics.update(metric_block(target[active_mask], reconstruction))
    metrics["reference_sound_speed_m_s"] = reference_c
    return InversionResult(target, full_recon, error, metrics)


def reconstruct_lesioning(
    prepared: PreparedSlice,
    active_mask: np.ndarray,
    matrix: np.ndarray,
    lesion_mask: np.ndarray,
    config: ApertureConfig,
) -> InversionResult:
    """Reconstruct the time-lapse lesion-induced sound-speed change."""

    target = np.zeros(prepared.sound_speed_m_s.shape, dtype=np.float32)
    target[lesion_mask] = config.lesion_delta_c_m_s / C_REF_M_S
    reconstruction, metrics = solve_contrast(matrix, target[active_mask], active_mask, config)

    full_recon = np.zeros_like(target)
    full_recon[active_mask] = reconstruction
    error = np.zeros_like(target)
    error[active_mask] = full_recon[active_mask] - target[active_mask]
    metrics.update(metric_block(target[active_mask], reconstruction))
    metrics["lesion_delta_c_m_s"] = config.lesion_delta_c_m_s
    metrics["equal_volume_dice"] = equal_volume_dice(
        reconstruction,
        lesion_mask[active_mask],
        negative=config.lesion_delta_c_m_s < 0.0,
    )
    metrics["lesion_cnr"] = contrast_to_noise(
        reconstruction,
        lesion_mask[active_mask],
    )
    return InversionResult(target, full_recon, error, metrics)


def reconstruct_subharmonic(
    prepared: PreparedSlice,
    active_mask: np.ndarray,
    matrix: np.ndarray,
    simulation: SimulationChannels,
    config: ApertureConfig,
) -> InversionResult:
    """Reconstruct lesion-localized subharmonic cavitation source density."""

    target = simulation.subharmonic_source.astype(np.float32)
    reconstruction, metrics = solve_contrast(matrix, target[active_mask], active_mask, config)

    full_recon = np.zeros_like(target)
    full_recon[active_mask] = reconstruction
    error = np.zeros_like(target)
    error[active_mask] = full_recon[active_mask] - target[active_mask]
    metrics.update(metric_block(target[active_mask], reconstruction))
    metrics["channel"] = "subharmonic"
    metrics["equal_volume_dice"] = equal_volume_dice(
        reconstruction,
        target[active_mask] > 0.0,
        negative=False,
    )
    metrics["lesion_cnr"] = contrast_to_noise(
        reconstruction,
        target[active_mask] > 0.0,
    )
    return InversionResult(target, full_recon, error, metrics)


def reconstruct_nonlinear(
    prepared: PreparedSlice,
    active_mask: np.ndarray,
    matrix: np.ndarray,
    simulation: SimulationChannels,
    config: ApertureConfig,
) -> InversionResult:
    """Reconstruct weak-nonlinear lesion susceptibility from harmonic rows."""

    target = (
        simulation.nonlinear_source.astype(np.float32)
        * abs(config.lesion_delta_c_m_s)
        / C_REF_M_S
    )
    reconstruction, metrics = solve_contrast(matrix, target[active_mask], active_mask, config)

    full_recon = np.zeros_like(target)
    full_recon[active_mask] = reconstruction
    error = np.zeros_like(target)
    error[active_mask] = full_recon[active_mask] - target[active_mask]
    metrics.update(metric_block(target[active_mask], reconstruction))
    metrics["channel"] = "nonlinear_harmonic"
    metrics["equal_volume_dice"] = equal_volume_dice(
        reconstruction,
        target[active_mask] > 0.0,
        negative=False,
    )
    metrics["lesion_cnr"] = contrast_to_noise(
        reconstruction,
        target[active_mask] > 0.0,
    )
    return InversionResult(target, full_recon, error, metrics)


def solve_contrast(
    matrix: np.ndarray,
    target: np.ndarray,
    active_mask: np.ndarray,
    config: ApertureConfig,
) -> tuple[np.ndarray, dict[str, float | int | list[float]]]:
    """Solve the regularized normal equations with diagonal-preconditioned CG."""

    target = np.asarray(target, dtype=np.float32)
    data = matrix @ target
    rhs = matrix.T @ data
    diag = (
        np.sum(matrix * matrix, axis=0)
        + config.regularization
        + config.smoothness_regularization * active_degree(active_mask)
    )
    x = np.zeros_like(rhs)
    r = rhs - normal_apply(matrix, x, active_mask, config)
    z = r / diag
    p = z.copy()
    rz_old = float(np.dot(r, z))
    initial_objective = objective(matrix, x, data, active_mask, config)
    history = [initial_objective]

    for _ in range(config.iterations):
        ap = normal_apply(matrix, p, active_mask, config)
        denom = float(np.dot(p, ap))
        if denom <= 0.0:
            break
        alpha = rz_old / denom
        x = x + alpha * p
        r = r - alpha * ap
        z = r / diag
        rz_new = float(np.dot(r, z))
        history.append(objective(matrix, x, data, active_mask, config))
        if rz_new <= 1.0e-16 * max(rz_old, 1.0):
            break
        beta = rz_new / rz_old
        p = z + beta * p
        rz_old = rz_new

    final_objective = history[-1]
    metrics: dict[str, float | int | list[float]] = {
        "measurements": int(matrix.shape[0]),
        "active_voxels": int(matrix.shape[1]),
        "iterations": int(len(history) - 1),
        "initial_objective": float(initial_objective),
        "final_objective": float(final_objective),
        "therapy_elements": int(config.element_count),
        "imaging_receivers": int(config.imaging_receiver_count),
        "imaging_receiver_samples": int(config.imaging_receiver_samples),
        "therapy_focal_radius_m": float(config.therapy_focal_radius_m),
        "therapy_lateral_extent_m": float(config.therapy_lateral_extent_m),
        "therapy_central_cutout_m": float(config.therapy_central_cutout_m),
        "tikhonov_regularization": float(config.regularization),
        "smoothness_regularization": float(config.smoothness_regularization),
        "objective_reduction": float(
            1.0 - final_objective / max(initial_objective, 1.0e-30)
        ),
        "objective_history": [float(v) for v in history],
    }
    return x.astype(np.float32), metrics


def normal_apply(
    matrix: np.ndarray,
    x: np.ndarray,
    active_mask: np.ndarray,
    config: ApertureConfig,
) -> np.ndarray:
    """Apply ``A.T A + lambda I`` without materializing the normal matrix."""

    return (
        matrix.T @ (matrix @ x)
        + config.regularization * x
        + config.smoothness_regularization * laplacian_apply(active_mask, x)
    )


def objective(
    matrix: np.ndarray,
    x: np.ndarray,
    data: np.ndarray,
    active_mask: np.ndarray,
    config: ApertureConfig,
) -> float:
    """Regularized least-squares objective."""

    residual = matrix @ x - data
    l_x = laplacian_apply(active_mask, x)
    return (
        0.5 * float(np.dot(residual, residual))
        + 0.5 * config.regularization * float(np.dot(x, x))
        + 0.5 * config.smoothness_regularization * float(np.dot(x, l_x))
    )


def lesion_core(mask: np.ndarray) -> np.ndarray:
    """Select a deterministic lesion core inside the segmented target."""

    dist = ndimage.distance_transform_edt(mask)
    if float(dist.max()) <= 1.0:
        return mask.copy()
    core = dist >= 0.45 * float(dist.max())
    return core if np.any(core) else mask.copy()
