use kwavers_grid::Grid;
use kwavers_signal::Signal;
use crate::source::transducers::focused::bowl::{BowlConfig, BowlTransducer};
use crate::source::Source;
use ndarray::Array3;
use std::collections::HashMap;
use std::fmt::Debug;
use std::sync::Arc;

type GridIndex = (usize, usize, usize);
type ElementMap = HashMap<GridIndex, Vec<usize>>;

#[derive(Debug)]
pub struct FocusedSource {
    pub(crate) transducer: BowlTransducer,
    /// dyn Signal is the runtime waveform boundary; bowl geometry remains concrete.
    signal: Arc<dyn Signal>,
    focus_delays: Vec<f64>,
    element_map: ElementMap,
}

impl FocusedSource {
    /// Create a focused source from a standard bowl configuration.
    ///
    /// This constructor preserves the historical config-first API and delegates
    /// geometry ownership to [`BowlTransducer::new`]. Use
    /// [`Self::from_transducer`] when the bowl aperture is already expressed by
    /// source-domain constructors such as angular bounds, axis-projection
    /// bounds, annular spans, or fixed element count.
    ///
    /// # Errors
    /// - Propagates any validation error returned by [`BowlTransducer::new`].
    ///
    pub fn new(
        config: BowlConfig,
        signal: Arc<dyn Signal>,
        grid: &Grid,
    ) -> kwavers_core::error::KwaversResult<Self> {
        let transducer = BowlTransducer::new(config)?;
        Ok(Self::from_transducer(transducer, signal, grid))
    }

    /// Create a focused source from an already constructed bowl transducer.
    ///
    /// ## Theorem
    ///
    /// For each bowl element `e_i` at position `x_i`, the adapter assigns `i`
    /// to exactly the Cartesian cell returned by
    /// [`Grid::position_to_indices`](kwavers_grid::Grid::position_to_indices).
    /// Therefore `create_mask` is the cellwise sum of the canonical bowl
    /// surface-area weights, and specialized bowl layouts generated by
    /// [`BowlTransducer`] enter the simulation without a parallel source model.
    #[must_use]
    pub fn from_transducer(
        transducer: BowlTransducer,
        signal: Arc<dyn Signal>,
        grid: &Grid,
    ) -> Self {
        let focus_delays = transducer.calculate_focus_delays();
        let element_map = build_element_map(&transducer, grid);

        Self {
            transducer,
            signal,
            focus_delays,
            element_map,
        }
    }
}

fn build_element_map(transducer: &BowlTransducer, grid: &Grid) -> ElementMap {
    let mut element_map: ElementMap = HashMap::with_capacity(transducer.element_count());
    for (element_index, &position) in transducer.element_positions().iter().enumerate() {
        if let Some(grid_index) = grid.position_to_indices(position[0], position[1], position[2]) {
            element_map
                .entry(grid_index)
                .or_default()
                .push(element_index);
        }
    }
    element_map
}

impl Source for FocusedSource {
    fn create_mask(&self, grid: &Grid) -> Array3<f64> {
        let mut mask = Array3::zeros((grid.nx, grid.ny, grid.nz));
        self.create_mask_into(grid, &mut mask);
        mask
    }

    fn create_mask_into(&self, grid: &Grid, mask: &mut Array3<f64>) {
        debug_assert_eq!(mask.dim(), (grid.nx, grid.ny, grid.nz));
        mask.fill(0.0);
        self.add_mask_into(grid, mask);
    }

    fn add_mask_into(&self, grid: &Grid, mask: &mut Array3<f64>) {
        debug_assert_eq!(mask.dim(), (grid.nx, grid.ny, grid.nz));

        for (key, indices) in &self.element_map {
            let (ix, iy, iz) = *key;
            if ix < grid.nx && iy < grid.ny && iz < grid.nz {
                let mut weight_sum = 0.0;
                for &idx in indices {
                    weight_sum += self.transducer.element_areas[idx];
                }
                mask[(ix, iy, iz)] += weight_sum;
            }
        }
    }

    fn amplitude(&self, t: f64) -> f64 {
        self.signal.amplitude(t)
    }

    fn positions(&self) -> Vec<(f64, f64, f64)> {
        self.transducer
            .element_positions
            .iter()
            .map(|p| (p[0], p[1], p[2]))
            .collect()
    }

    fn signal(&self) -> &dyn Signal {
        self.signal.as_ref()
    }

    fn get_source_term(&self, t: f64, x: f64, y: f64, z: f64, grid: &Grid) -> f64 {
        // Find grid index for (x, y, z)
        if let Some((ix, iy, iz)) = grid.position_to_indices(x, y, z) {
            if let Some(indices) = self.element_map.get(&(ix, iy, iz)) {
                let mut sum_val = 0.0;
                for &i in indices {
                    let delay = self.focus_delays[i];
                    let weight = self.transducer.element_areas[i];
                    sum_val += weight * self.signal.amplitude(t - delay);
                }
                return sum_val;
            }
        }
        0.0
    }

    fn focal_point(&self) -> Option<(f64, f64, f64)> {
        let f = self.transducer.config.focus;
        Some((f[0], f[1], f[2]))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kwavers_core::constants::numerical::MPA_TO_PA;

    #[derive(Clone, Debug)]
    struct ConstantSignal {
        amplitude_pa: f64,
    }

    impl ConstantSignal {
        fn new(amplitude_pa: f64) -> Self {
            Self { amplitude_pa }
        }
    }

    impl Signal for ConstantSignal {
        fn amplitude(&self, _t: f64) -> f64 {
            self.amplitude_pa
        }

        fn frequency(&self, _t: f64) -> f64 {
            0.0
        }

        fn phase(&self, _t: f64) -> f64 {
            0.0
        }

        fn clone_box(&self) -> Box<dyn Signal> {
            Box::new(self.clone())
        }
    }

    #[test]
    fn from_transducer_accepts_axis_projected_bowl_layout() {
        let config = BowlConfig::from_vertex_focus(
            [0.0, 0.0, 0.16],
            [0.0, 0.0, 0.0],
            0.32,
            650.0e3,
            MPA_TO_PA,
        );
        let bowl = BowlTransducer::with_axis_projection_bounds(config, -0.28, 0.98, 16).unwrap();
        let expected_area: f64 = bowl.element_areas().iter().sum();

        let mut grid = Grid::new(25, 25, 13, 0.02, 0.02, 0.02).unwrap();
        grid.origin = [-0.24, -0.24, -0.06];

        let source =
            FocusedSource::from_transducer(bowl, Arc::new(ConstantSignal::new(2.0)), &grid);
        let mask = source.create_mask(&grid);
        let mapped_area: f64 = mask.iter().sum();

        assert_eq!(source.transducer.element_count(), 16);
        assert_eq!(source.focal_point(), Some((0.0, 0.0, 0.0)));
        assert_close(mapped_area, expected_area);
        for position in source.positions() {
            assert!(
                grid.position_to_indices(position.0, position.1, position.2)
                    .is_some(),
                "source position {position:?} must map into the grid"
            );
        }
    }

    #[test]
    fn source_term_uses_preconstructed_bowl_area_and_delay() {
        let config = BowlConfig {
            radius_of_curvature: 0.08,
            diameter: 0.04,
            center: [0.0, 0.0, -0.08],
            focus: [0.0, 0.0, 0.0],
            frequency: 1.25e6,
            amplitude: 1.0e5,
            apply_directivity: false,
            ..Default::default()
        };
        let bowl = BowlTransducer::with_element_count(config, 1).unwrap();
        let element_position = bowl.element_positions()[0];
        let element_area = bowl.element_areas()[0];
        let focus_delay = bowl.calculate_focus_delays()[0];

        let mut grid = Grid::new(11, 11, 11, 0.01, 0.01, 0.01).unwrap();
        grid.origin = [-0.05, -0.05, -0.10];

        let source =
            FocusedSource::from_transducer(bowl, Arc::new(ConstantSignal::new(3.0)), &grid);
        let actual = source.get_source_term(
            focus_delay,
            element_position[0],
            element_position[1],
            element_position[2],
            &grid,
        );

        assert_close(actual, 3.0 * element_area);
    }

    fn assert_close(actual: f64, expected: f64) {
        let tolerance = 64.0 * f64::EPSILON * expected.abs().max(1.0);
        assert!(
            (actual - expected).abs() <= tolerance,
            "actual {actual}, expected {expected}, tolerance {tolerance}"
        );
    }
}
