//! Bowl transducer implementation
//!
//! Provides focused bowl transducer geometry and source generation.

use kwavers_core::{
        constants::numerical::{MHZ_TO_HZ, MPA_TO_PA},
        constants::SOUND_SPEED_WATER,
        error::{KwaversError, KwaversResult, ValidationError},
    };
use crate::grid::Grid;
use ndarray::{Array3, Zip};

use super::cap::{SphericalCapConfig, SphericalCapLayout};
use super::validation::{
    field_validation_error, positive_finite, validate_element_count, validate_finite_field,
    validate_finite_vector, validate_positive_finite_field,
};
use kwavers_core::constants::numerical::{FOUR_PI, TWO_PI};

mod presets;
mod projection;
mod span;

pub use span::BowlAngularBounds;

#[cfg(test)]
mod tests;

/// Configuration for a focused bowl transducer
#[derive(Debug, Clone)]
pub struct BowlConfig {
    /// Radius of curvature (m)
    pub radius_of_curvature: f64,

    /// Diameter of the bowl aperture (m)
    pub diameter: f64,

    /// Center position [x, y, z] (m)
    pub center: [f64; 3],

    /// Focus position [x, y, z] (m)
    pub focus: [f64; 3],

    /// Operating frequency (Hz)
    pub frequency: f64,

    /// Source amplitude (Pa)
    pub amplitude: f64,

    /// Phase delay (radians)
    pub phase: f64,

    /// Element size for discretization (m)
    pub element_size: Option<f64>,

    /// Apply directivity weighting
    pub apply_directivity: bool,
}

#[derive(Debug, Clone, Copy, PartialEq)]
enum BowlDiscretization {
    ElementSize(f64),
    ElementCount(usize),
}

impl Default for BowlConfig {
    fn default() -> Self {
        Self {
            radius_of_curvature: 0.064, // 64mm
            diameter: 0.064,            // 64mm
            center: [0.0, 0.0, 0.0],
            focus: [0.0, 0.0, 0.064], // Focus at radius
            frequency: MHZ_TO_HZ,     // 1 MHz
            amplitude: MPA_TO_PA,     // 1 MPa
            phase: 0.0,
            element_size: None,
            apply_directivity: true,
        }
    }
}

/// Focused bowl transducer (makeBowl equivalent)
#[derive(Debug)]
pub struct BowlTransducer {
    pub(crate) config: BowlConfig,
    /// Discretized element positions
    pub(crate) element_positions: Vec<[f64; 3]>,
    /// Element normals for directivity
    pub(crate) element_normals: Vec<[f64; 3]>,
    /// Element areas for weighting
    pub(crate) element_areas: Vec<f64>,
}

impl BowlTransducer {
    /// Create a new bowl transducer
    /// # Errors
    /// - Returns [`KwaversError::Validation`] if the precondition for a Validation-class constraint is violated.
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub fn new(config: BowlConfig) -> KwaversResult<Self> {
        Self::validate_config(&config)?;
        let element_size = default_or_configured_element_size(&config)?;
        Self::from_validated_discretization(config, BowlDiscretization::ElementSize(element_size))
    }

    /// Create a bowl transducer with an explicit focused-cap element count.
    ///
    /// This constructor supports fixed-count hemispherical or partial-bowl
    /// layouts such as 1024-element transcranial arrays without introducing an
    /// anatomy-specific source type. Element positions, normals, and equal-area
    /// weights remain generated by the same spherical-cap source geometry used
    /// by [`Self::new`].
    ///
    /// # Errors
    /// - Returns [`KwaversError::Validation`] when the count or bowl domain is invalid.
    /// - Propagates any [`KwaversError`] returned by spherical-cap layout generation.
    pub fn with_element_count(config: BowlConfig, element_count: usize) -> KwaversResult<Self> {
        validate_element_count(element_count)?;
        Self::from_discretization(config, BowlDiscretization::ElementCount(element_count))
    }

    fn from_discretization(
        config: BowlConfig,
        discretization: BowlDiscretization,
    ) -> KwaversResult<Self> {
        Self::validate_config(&config)?;
        Self::from_validated_discretization(config, discretization)
    }

    fn from_validated_discretization(
        config: BowlConfig,
        discretization: BowlDiscretization,
    ) -> KwaversResult<Self> {
        if config.diameter > 2.0 * config.radius_of_curvature {
            return Err(KwaversError::Validation(ValidationError::FieldValidation {
                field: "diameter".to_owned(),
                value: config.diameter.to_string(),
                constraint: "Diameter cannot exceed 2 * radius_of_curvature".to_owned(),
            }));
        }

        // Discretize bowl surface
        let (positions, normals, areas) = Self::discretize_bowl(&config, discretization)?;

        Ok(Self {
            config,
            element_positions: positions,
            element_normals: normals,
            element_areas: areas,
        })
    }

    /// Borrow the generated element center positions [m].
    #[must_use]
    pub fn element_positions(&self) -> &[[f64; 3]] {
        &self.element_positions
    }

    /// Borrow unit normals pointing from each element toward the acoustic focus.
    #[must_use]
    pub fn element_normals(&self) -> &[[f64; 3]] {
        &self.element_normals
    }

    /// Borrow equal surface-area weights [m²] represented by each element.
    #[must_use]
    pub fn element_areas(&self) -> &[f64] {
        &self.element_areas
    }

    /// Number of generated source elements.
    #[must_use]
    pub fn element_count(&self) -> usize {
        self.element_positions.len()
    }

    fn validate_config(config: &BowlConfig) -> KwaversResult<()> {
        validate_positive_finite_field("radius_of_curvature", config.radius_of_curvature)?;
        validate_positive_finite_field("diameter", config.diameter)?;
        validate_positive_finite_field("frequency", config.frequency)?;
        validate_finite_field("amplitude", config.amplitude)?;
        validate_finite_field("phase", config.phase)?;
        validate_finite_vector("center", config.center)?;
        validate_finite_vector("focus", config.focus)?;

        let axis = sub3(config.focus, config.center);
        if !positive_finite(norm3(axis)) {
            return Err(field_validation_error(
                "focus",
                format!("{:?}", config.focus),
                "must differ from center to define the bowl acoustic axis",
            ));
        }

        Ok(())
    }

    /// Discretize the bowl surface into elements
    /// # Errors
    /// - Returns [`Err`] if an internal constraint is violated.
    ///
    fn discretize_bowl(
        config: &BowlConfig,
        discretization: BowlDiscretization,
    ) -> KwaversResult<(Vec<[f64; 3]>, Vec<[f64; 3]>, Vec<f64>)> {
        let r = config.radius_of_curvature;
        let a = config.diameter / 2.0;
        let theta_max = (a / r).asin();
        let cap_area = spherical_cap_area(r, theta_max);
        let target_count = match discretization {
            BowlDiscretization::ElementSize(element_size) => {
                element_count_from_area(cap_area, element_size)?
            }
            BowlDiscretization::ElementCount(element_count) => element_count,
        };
        let axis = sub3(config.focus, config.center);
        let axis_unit = normalize3(axis).ok_or_else(|| {
            field_validation_error(
                "focus",
                format!("{:?}", config.focus),
                "must differ from center to define the bowl acoustic axis",
            )
        })?;
        let curvature_center = add3(config.center, scale3(axis_unit, r));
        let layout = SphericalCapLayout::new(SphericalCapConfig::focused_cap(
            target_count,
            r,
            curvature_center,
            axis,
            0.0,
            theta_max,
        ))?;

        let mut positions = Vec::with_capacity(layout.elements().len());
        let mut normals = Vec::with_capacity(layout.elements().len());
        let mut areas = Vec::with_capacity(layout.elements().len());

        for element in layout.elements() {
            positions.push(element.position_m);
            normals.push(element.normal_to_focus);
            areas.push(element.area_weight_m2);
        }

        Ok((positions, normals, areas))
    }

    /// Generate source distribution on a Cartesian grid.
    ///
    /// ## Theorem
    ///
    /// Each focused-bowl element contributes the retarded monopole term
    ///
    /// ```text
    /// p_i(x,t) = A_i S_i D_i(x) sin(omega (t - tau_i) + phi) / (4 pi |x - x_i|)
    /// ```
    ///
    /// where `S_i` is the element area weight, `D_i` is optional cosine
    /// directivity, and `tau_i = |x_focus - x_i| / c_water`. Grid coordinates
    /// are evaluated as `origin + index * spacing` independently per axis.
    ///
    /// # Errors
    /// - Returns [`Err`] if an internal constraint is violated.
    ///
    pub fn generate_source(&self, grid: &Grid, time: f64) -> KwaversResult<Array3<f64>> {
        let mut source = Array3::zeros((grid.nx, grid.ny, grid.nz));
        let omega = TWO_PI * self.config.frequency;
        let focus_delays = self.calculate_focus_delays();

        Zip::indexed(&mut source).par_for_each(|(ix, iy, iz), cell| {
            let point = [
                (ix as f64).mul_add(grid.dx, grid.origin[0]),
                (iy as f64).mul_add(grid.dy, grid.origin[1]),
                (iz as f64).mul_add(grid.dz, grid.origin[2]),
            ];
            *cell = self.pressure_at(point, time, omega, &focus_delays);
        });

        Ok(source)
    }

    fn pressure_at(&self, point: [f64; 3], time: f64, omega: f64, focus_delays: &[f64]) -> f64 {
        let mut pressure = 0.0;

        for (i, &pos) in self.element_positions.iter().enumerate() {
            let r = (point[2] - pos[2])
                .mul_add(
                    point[2] - pos[2],
                    (point[1] - pos[1]).mul_add(point[1] - pos[1], (point[0] - pos[0]).powi(2)),
                )
                .sqrt();

            if r > 0.0 {
                let directivity = if self.config.apply_directivity {
                    self.calculate_directivity(i, point)
                } else {
                    1.0
                };
                let phase = omega * (time - focus_delays[i]) + self.config.phase;
                pressure +=
                    self.config.amplitude * self.element_areas[i] * directivity * phase.sin()
                        / (FOUR_PI * r);
            }
        }

        pressure
    }

    /// Calculate time delays for focusing
    pub(crate) fn calculate_focus_delays(&self) -> Vec<f64> {
        let speed_of_sound = SOUND_SPEED_WATER;

        self.element_positions
            .iter()
            .map(|&pos| {
                let distance = (self.config.focus[2] - pos[2])
                    .mul_add(
                        self.config.focus[2] - pos[2],
                        (self.config.focus[1] - pos[1]).mul_add(
                            self.config.focus[1] - pos[1],
                            (self.config.focus[0] - pos[0]).powi(2),
                        ),
                    )
                    .sqrt();
                distance / speed_of_sound
            })
            .collect()
    }

    /// Calculate directivity for an element
    fn calculate_directivity(&self, element_idx: usize, target: [f64; 3]) -> f64 {
        let pos = self.element_positions[element_idx];
        let normal = self.element_normals[element_idx];

        // Vector from element to target
        let dir = [target[0] - pos[0], target[1] - pos[1], target[2] - pos[2]];
        let dir_mag = dir[2]
            .mul_add(dir[2], dir[1].mul_add(dir[1], dir[0].powi(2)))
            .sqrt();

        if dir_mag > 0.0 {
            // Cosine of angle between normal and direction
            let cos_theta =
                normal[2].mul_add(dir[2], normal[0].mul_add(dir[0], normal[1] * dir[1])) / dir_mag;

            // Cosine directivity pattern
            if cos_theta > 0.0 {
                cos_theta
            } else {
                0.0
            }
        } else {
            1.0
        }
    }

    /// Get analytical solution using O'Neil's formula
    ///
    /// O'Neil's solution provides the on-axis pressure field for a spherically
    /// focused transducer. The formula involves complex exponentials representing
    /// the phase accumulation from different parts of the curved surface.
    ///
    /// Reference: O'Neil, H. T. (1949). "Theory of focusing radiators."
    /// The Journal of the Acoustical Society of America, 21(5), 516-526.
    #[must_use]
    pub fn oneil_solution(&self, z: f64, time: f64) -> f64 {
        // O'Neil's solution for on-axis pressure of a focused bowl transducer
        let r = self.config.radius_of_curvature;
        let a = self.config.diameter / 2.0;
        let k = TWO_PI * self.config.frequency / SOUND_SPEED_WATER; // Wave number
        let omega = TWO_PI * self.config.frequency; // Angular frequency
        let _c = SOUND_SPEED_WATER; // Speed of sound in water

        // Geometric parameters
        // h is the height of the spherical cap
        let h = r - r.mul_add(r, -(a * a)).sqrt();

        // Distance from transducer center to field point
        let d1 = z.abs();
        // Distance from edge of spherical cap to field point
        let d2 = (z - (r - h)).mul_add(z - (r - h), a * a).sqrt();

        // O'Neil's formula for on-axis pressure
        // The pressure is the result of interference between waves from the center
        // and edge of the bowl, accounting for their phase difference
        let phase_diff = k * (d2 - d1);

        // Complex pressure amplitude using proper formulation
        // P(z,t) = P0 * |exp(ikd1) - exp(ikd2)| * exp(i*omega*t) / (2*d1)
        // For magnitude: |exp(ikd1) - exp(ikd2)| = 2*|sin(phase_diff/2)|
        let p_amplitude = if d1 > 0.0 {
            self.config.amplitude * 2.0 * (phase_diff / 2.0).sin().abs() / d1
        } else {
            // At z=0, use limiting value
            self.config.amplitude * k * h
        };

        // Add time-varying component

        p_amplitude * (omega * time - k * d1 + self.config.phase).sin()
    }
}

fn element_count_from_area(area_m2: f64, element_size_m: f64) -> KwaversResult<usize> {
    let count = (area_m2 / element_size_m.powi(2)).ceil();
    if !count.is_finite() || count < 1.0 || count > usize::MAX as f64 {
        return Err(field_validation_error(
            "element_size",
            element_size_m.to_string(),
            "must produce a finite representable spherical-cap element count",
        ));
    }
    Ok(count as usize)
}

fn default_or_configured_element_size(config: &BowlConfig) -> KwaversResult<f64> {
    let element_size = config.element_size.unwrap_or_else(|| {
        let wavelength = SOUND_SPEED_WATER / config.frequency;
        wavelength / 4.0
    });
    validate_positive_finite_field("element_size", element_size)?;
    Ok(element_size)
}

fn spherical_cap_area(radius_m: f64, theta_max_rad: f64) -> f64 {
    TWO_PI * radius_m * radius_m * (1.0 - theta_max_rad.cos())
}

fn add3(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
}

fn sub3(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [a[0] - b[0], a[1] - b[1], a[2] - b[2]]
}

fn scale3(vector: [f64; 3], scale: f64) -> [f64; 3] {
    [vector[0] * scale, vector[1] * scale, vector[2] * scale]
}

fn norm3(vector: [f64; 3]) -> f64 {
    vector[0]
        .mul_add(
            vector[0],
            vector[1].mul_add(vector[1], vector[2] * vector[2]),
        )
        .sqrt()
}

fn normalize3(vector: [f64; 3]) -> Option<[f64; 3]> {
    if !vector.iter().all(|component| component.is_finite()) {
        return None;
    }
    let norm = norm3(vector);
    positive_finite(norm).then(|| scale3(vector, norm.recip()))
}
