//! Utility functions for focused transducers
//!
//! Provides helper functions for creating common transducer configurations.

use super::bowl::{BowlConfig, BowlTransducer};
use super::multi_bowl::MultiBowlArray;
use super::validation::{
    field_validation_error, validate_finite_vector, validate_positive_finite_field,
};
use kwavers_core::constants::numerical::MPA_TO_PA;
use kwavers_core::constants::SOUND_SPEED_WATER;
use kwavers_core::error::KwaversResult;

pub use super::multi_bowl::ApodizationType;
use kwavers_core::constants::numerical::TWO_PI;

/// Helper function to create a spherical section bowl.
///
/// The helper keeps the public utility API centered on source-domain geometry:
/// `center` is the bowl vertex, the acoustic focus is one curvature radius along
/// the positive z axis, and `diameter` is the active cap chord diameter.
///
/// # Theorem
///
/// For `R = radius` and `C = center`, this constructor is equivalent to
/// [`BowlConfig::from_focus_axis`] with `F = C + R e_z` and
/// `axis = e_z`. Therefore the generated bowl satisfies `||F - C|| = R` and
/// every element generated by [`BowlTransducer`] lies on the sphere centered at
/// `F` with radius `R`.
///
/// # Errors
///
/// Returns a validation error when any geometric or signal parameter violates
/// the focused-bowl source domain.
///
pub fn make_bowl(
    radius: f64,
    diameter: f64,
    center: [f64; 3],
    frequency: f64,
    amplitude: f64,
) -> KwaversResult<BowlTransducer> {
    let focus = [center[0], center[1], center[2] + radius];
    let config = BowlConfig::from_focus_axis(
        focus,
        [0.0, 0.0, 1.0],
        radius,
        diameter,
        frequency,
        amplitude,
    )?;

    BowlTransducer::new(config)
}

/// Create concentric annular active bands on one focused spherical bowl.
///
/// The aperture radii are measured in the plane normal to the vertex-to-focus
/// axis. All rings share `radius_of_curvature` and the acoustic focus
/// `vertex + [0, 0, radius_of_curvature]`; only their polar-angle span differs.
///
/// # Theorem
///
/// For a spherical focused bowl with curvature radius `R`, aperture radius
/// `a = R sin(theta)`. An annular band `[a_i, a_o]` therefore maps to
/// `theta in [asin(a_i/R), asin(a_o/R)]` and has surface area
/// `2 pi R^2 (cos(theta_i) - cos(theta_o))`. Splitting the aperture by this
/// mapping preserves the same source surface represented by
/// [`BowlTransducer::with_polar_bounds`].
///
/// # Errors
///
/// Returns [`kwavers_core::error::KwaversError::Validation`] when the curvature,
/// aperture radii, ring count, vertex, or frequency violates the focused-bowl
/// source domain.
///
pub fn make_annular_array(
    radius_of_curvature: f64,
    inner_aperture_radius: f64,
    outer_aperture_radius: f64,
    n_rings: usize,
    vertex: [f64; 3],
    frequency: f64,
) -> KwaversResult<MultiBowlArray> {
    validate_annular_array_domain(
        radius_of_curvature,
        inner_aperture_radius,
        outer_aperture_radius,
        n_rings,
        vertex,
        frequency,
    )?;

    let focus = [vertex[0], vertex[1], vertex[2] + radius_of_curvature];
    let base_config = BowlConfig::from_vertex_focus(
        vertex,
        focus,
        2.0 * outer_aperture_radius,
        frequency,
        MPA_TO_PA,
    );
    let mut bowls = Vec::with_capacity(n_rings);

    for i in 0..n_rings {
        let ring_inner = inner_aperture_radius
            + (outer_aperture_radius - inner_aperture_radius) * i as f64 / n_rings as f64;
        let ring_outer = inner_aperture_radius
            + (outer_aperture_radius - inner_aperture_radius) * (i + 1) as f64 / n_rings as f64;
        let theta_min = (ring_inner / radius_of_curvature).asin();
        let theta_max = (ring_outer / radius_of_curvature).asin();
        let element_count =
            annular_ring_element_count(radius_of_curvature, theta_min, theta_max, frequency)?;
        bowls.push(BowlTransducer::with_polar_bounds(
            base_config.clone(),
            theta_min,
            theta_max,
            element_count,
        )?);
    }

    MultiBowlArray::from_bowls(bowls)
}

fn validate_annular_array_domain(
    radius_of_curvature: f64,
    inner_aperture_radius: f64,
    outer_aperture_radius: f64,
    n_rings: usize,
    vertex: [f64; 3],
    frequency: f64,
) -> KwaversResult<()> {
    validate_positive_finite_field("radius_of_curvature", radius_of_curvature)?;
    validate_positive_finite_field("outer_aperture_radius", outer_aperture_radius)?;
    validate_positive_finite_field("frequency", frequency)?;
    validate_finite_vector("vertex", vertex)?;
    if !(inner_aperture_radius.is_finite() && inner_aperture_radius >= 0.0) {
        return Err(field_validation_error(
            "inner_aperture_radius",
            inner_aperture_radius.to_string(),
            "must be finite and nonnegative",
        ));
    }
    if inner_aperture_radius >= outer_aperture_radius {
        return Err(field_validation_error(
            "aperture_radii",
            format!("[{inner_aperture_radius}, {outer_aperture_radius}]"),
            "must satisfy inner_aperture_radius < outer_aperture_radius",
        ));
    }
    if outer_aperture_radius > radius_of_curvature {
        return Err(field_validation_error(
            "outer_aperture_radius",
            outer_aperture_radius.to_string(),
            "must not exceed radius_of_curvature",
        ));
    }
    if n_rings == 0 {
        return Err(field_validation_error(
            "n_rings",
            n_rings.to_string(),
            "must be at least one",
        ));
    }
    Ok(())
}

fn annular_ring_element_count(
    radius_of_curvature: f64,
    theta_min: f64,
    theta_max: f64,
    frequency: f64,
) -> KwaversResult<usize> {
    let area =
        TWO_PI * radius_of_curvature * radius_of_curvature * (theta_min.cos() - theta_max.cos());
    let element_size = SOUND_SPEED_WATER / frequency / 4.0;
    let count = (area / element_size.powi(2)).ceil();
    if !count.is_finite() || count < 1.0 || count > usize::MAX as f64 {
        return Err(field_validation_error(
            "annular_ring_area",
            area.to_string(),
            "must produce a finite representable element count",
        ));
    }
    Ok(count as usize)
}

#[cfg(test)]
mod tests {
    use super::*;
    use kwavers_core::constants::numerical::MHZ_TO_HZ;
    use kwavers_core::error::{KwaversError, ValidationError};
    use crate::grid::Grid;
    use std::f64::consts::PI;

    #[test]
    fn test_bowl_transducer_creation() {
        let config = BowlConfig::default();
        let bowl = BowlTransducer::new(config).unwrap();

        assert!(!bowl.element_positions.is_empty());
        assert_eq!(bowl.element_positions.len(), bowl.element_normals.len());
        assert_eq!(bowl.element_positions.len(), bowl.element_areas.len());
    }

    #[test]
    fn test_bowl_focusing() {
        let config = BowlConfig {
            radius_of_curvature: 0.05,
            diameter: 0.04,
            center: [0.0, 0.0, 0.0],
            focus: [0.0, 0.0, 0.05],
            frequency: MHZ_TO_HZ,
            amplitude: MPA_TO_PA,
            ..Default::default()
        };

        let bowl = BowlTransducer::new(config).unwrap();
        let delays = bowl.calculate_focus_delays();

        // All delays should be positive
        for delay in delays {
            assert!(delay >= 0.0);
        }
    }

    #[test]
    fn make_bowl_uses_focus_axis_source_constructor() {
        let center = [0.01, -0.02, 0.03];
        let radius = 0.07;
        let diameter = 0.04;
        let bowl = make_bowl(radius, diameter, center, 1.2 * MHZ_TO_HZ, 2.0 * MPA_TO_PA).unwrap();

        assert_eq!(bowl.config.center, center);
        assert_eq!(
            bowl.config.focus,
            [center[0], center[1], center[2] + radius]
        );
        assert_close(bowl.config.radius_of_curvature, radius);
        assert_close(bowl.config.diameter, diameter);

        for position in bowl.element_positions() {
            let distance_to_focus = ((position[0] - bowl.config.focus[0]).powi(2)
                + (position[1] - bowl.config.focus[1]).powi(2)
                + (position[2] - bowl.config.focus[2]).powi(2))
            .sqrt();
            assert_close(distance_to_focus, radius);
        }
    }

    #[test]
    fn test_multi_bowl_array() {
        let configs = vec![
            BowlConfig {
                radius_of_curvature: 0.05,
                diameter: 0.03,
                center: [0.0, 0.0, 0.0],
                ..Default::default()
            },
            BowlConfig {
                radius_of_curvature: 0.06,
                diameter: 0.04,
                center: [0.01, 0.0, 0.0],
                ..Default::default()
            },
        ];

        let array = MultiBowlArray::new(configs).unwrap();
        assert_eq!(array.bowls.len(), 2);
    }

    #[test]
    fn annular_array_uses_common_curvature_focus_and_radial_bands() {
        let array = make_annular_array(0.08, 0.02, 0.04, 2, [0.0, 0.0, 0.0], MHZ_TO_HZ).unwrap();
        let radial_bounds = [(0.02, 0.03), (0.03, 0.04)];

        assert_eq!(array.bowls.len(), 2);
        for (bowl, (inner, outer)) in array.bowls.iter().zip(radial_bounds) {
            assert_close(bowl.config.radius_of_curvature, 0.08);
            assert_eq!(bowl.config.center, [0.0, 0.0, 0.0]);
            assert_eq!(bowl.config.focus, [0.0, 0.0, 0.08]);
            assert!(bowl.element_count() > 0);

            let summed_area: f64 = bowl.element_areas().iter().sum();
            let theta_min = (inner / 0.08_f64).asin();
            let theta_max = (outer / 0.08_f64).asin();
            let expected_area = 2.0 * PI * 0.08_f64.powi(2) * (theta_min.cos() - theta_max.cos());
            assert_close(summed_area, expected_area);

            for position in bowl.element_positions() {
                let aperture_radius = position[0].hypot(position[1]);
                assert!(
                    aperture_radius >= inner - 1.0e-12 && aperture_radius <= outer + 1.0e-12,
                    "aperture radius {aperture_radius} outside [{inner}, {outer}]"
                );
            }
        }
    }

    #[test]
    fn annular_array_rejects_invalid_domains() {
        let error =
            make_annular_array(0.08, 0.04, 0.02, 2, [0.0, 0.0, 0.0], MHZ_TO_HZ).unwrap_err();
        match error {
            KwaversError::Validation(ValidationError::FieldValidation { field, .. }) => {
                assert_eq!(field, "aperture_radii");
            }
            other => panic!("expected aperture radii validation error, got {other:?}"),
        }

        let excessive_aperture =
            make_annular_array(0.08, 0.02, 0.09, 2, [0.0, 0.0, 0.0], MHZ_TO_HZ).unwrap_err();
        match excessive_aperture {
            KwaversError::Validation(ValidationError::FieldValidation { field, .. }) => {
                assert_eq!(field, "outer_aperture_radius");
            }
            other => panic!("expected outer aperture validation error, got {other:?}"),
        }

        let zero_rings =
            make_annular_array(0.08, 0.02, 0.04, 0, [0.0, 0.0, 0.0], MHZ_TO_HZ).unwrap_err();
        match zero_rings {
            KwaversError::Validation(ValidationError::FieldValidation { field, .. }) => {
                assert_eq!(field, "n_rings");
            }
            other => panic!("expected ring-count validation error, got {other:?}"),
        }
    }

    /// Test multi-bowl array with phase shifts (COMPREHENSIVE - Tier 3)
    ///
    /// This test generates sources on a 32³ grid with phase shifts.
    /// Execution time: >60s, classified as Tier 3 comprehensive validation.
    /// # Panics
    /// - Panics if an internal invariant assumed to hold at this call site is violated.
    ///
    #[test]
    #[ignore = "Tier 3: Comprehensive validation (>60s execution time)"]
    fn test_multi_bowl_phases() {
        // Create two bowls with different phases
        let config1 = BowlConfig {
            diameter: 0.03,
            radius_of_curvature: 0.05,
            focus: [0.0, 0.0, 0.05],
            frequency: MHZ_TO_HZ,
            amplitude: MPA_TO_PA,
            phase: 0.0,
            ..Default::default()
        };

        let config2 = BowlConfig {
            diameter: 0.03,
            radius_of_curvature: 0.05,
            focus: [0.0, 0.0, 0.05],
            frequency: MHZ_TO_HZ,
            amplitude: MPA_TO_PA,
            phase: PI / 2.0, // 90 degree phase shift
            ..Default::default()
        };

        let multi_array = MultiBowlArray::new(vec![config1, config2]).unwrap();
        let grid = Grid::new(32, 32, 32, 0.001, 0.001, 0.001).unwrap();

        // Generate sources at different times
        let source_t0 = multi_array.generate_source(&grid, 0.0).unwrap();
        let source_t1 = multi_array.generate_source(&grid, 0.25e-6).unwrap(); // Quarter period

        // The sources should be different due to phase shifts
        let diff = &source_t1 - &source_t0;
        let max_diff = diff.iter().fold(0.0f64, |a, &b| a.max(b.abs()));
        assert!(
            max_diff > 0.0,
            "Phase shifts should cause time-varying fields"
        );
    }

    /// Test multi-bowl array with phase shifts (FAST - Tier 1)
    ///
    /// Fast version with reduced grid (8³) for CI/CD smoke test.
    /// Execution time: <1s, classified as Tier 1 fast validation.
    /// # Panics
    /// - Panics if an internal invariant assumed to hold at this call site is violated.
    ///
    #[test]
    fn test_multi_bowl_phases_fast() {
        // Create two bowls with different phases
        let config1 = BowlConfig {
            diameter: 0.03,
            radius_of_curvature: 0.05,
            focus: [0.0, 0.0, 0.05],
            frequency: MHZ_TO_HZ,
            amplitude: MPA_TO_PA,
            phase: 0.0,
            ..Default::default()
        };

        let config2 = BowlConfig {
            diameter: 0.03,
            radius_of_curvature: 0.05,
            focus: [0.0, 0.0, 0.05],
            frequency: MHZ_TO_HZ,
            amplitude: MPA_TO_PA,
            phase: PI / 2.0, // 90 degree phase shift
            ..Default::default()
        };

        let multi_array = MultiBowlArray::new(vec![config1, config2]).unwrap();
        let grid = Grid::new(8, 8, 8, 0.001, 0.001, 0.001).unwrap();

        // Generate sources at different times
        let source_t0 = multi_array.generate_source(&grid, 0.0).unwrap();
        let source_t1 = multi_array.generate_source(&grid, 0.25e-6).unwrap(); // Quarter period

        // The sources should be different due to phase shifts
        let diff = &source_t1 - &source_t0;
        let max_diff = diff.iter().fold(0.0f64, |a, &b| a.max(b.abs()));
        assert!(
            max_diff > 0.0,
            "Phase shifts should cause time-varying fields"
        );
    }

    #[test]
    fn test_oneil_solution() {
        use approx::assert_relative_eq;

        let bowl = make_bowl(0.064, 0.064, [0.0, 0.0, 0.0], MHZ_TO_HZ, MPA_TO_PA).unwrap();

        let focus_distance = 0.064; // radius of curvature = geometric focus [m]
        let frequency = MHZ_TO_HZ;
        let c = kwavers_core::constants::SOUND_SPEED_WATER;
        let a = bowl.config.diameter / 2.0; // aperture radius = 0.032 m
        let r = bowl.config.radius_of_curvature; // 0.064 m
        let k = 2.0 * PI * frequency / c;
        let h = r - (r * r - a * a).sqrt(); // spherical-cap height

        // O'Neil (1949) on-axis amplitude at axial position z:
        //   |P(z)| = P₀ · 2 · |sin(k (d₂ − d₁) / 2)| / d₁
        // where d₁ = z, d₂ = √((z − (r−h))² + a²).
        //
        // Note: the argument is k(d₂−d₁)/2, NOT kh/2.  At z = focus = r
        // these differ because d₂ = √(h² + a²) ≠ h.  The absolute value of
        // sin is required: sin(k(d₂−d₁)/2) can be negative for many geometries.
        let f = r - h; // distance from bowl apex to focus along axis
        let d2_focus = ((focus_distance - f).powi(2) + a * a).sqrt();
        let phase_at_focus = k * (d2_focus - focus_distance);
        let expected_amplitude =
            bowl.config.amplitude * 2.0 * (phase_at_focus / 2.0).sin().abs() / focus_distance;

        // Peak pressure at z occurs at t = d₁/c + T/4 (propagation delay + sin max).
        // Using t = T/4 only is wrong because it ignores the k·d₁ phase in
        //   P(z, t) = P_amplitude · sin(ω t − k d₁ + φ).
        let peak_time = |z: f64| z / c + 1.0 / (4.0 * frequency);

        // Amplitude at the focal point.
        let p_focus_max = bowl
            .oneil_solution(focus_distance, peak_time(focus_distance))
            .abs();
        assert_relative_eq!(
            p_focus_max,
            expected_amplitude,
            epsilon = 0.01 * expected_amplitude
        );

        // Focusing: near-field amplitude must exceed far-field amplitude.
        //
        // For this geometry (r=0.064 m, a=0.032 m, F# = 1.0), the on-axis O'Neil
        // field exhibits near-field interference maxima before the geometric focus.
        // The pressure maximum is NOT necessarily at z = r (the centre of curvature)
        // — it can appear earlier for strongly focused bowls.  The physically
        // correct "focusing" check is that the near-field peak (here at z ≈ 0.05 m)
        // exceeds the far-field amplitude (z = 0.20 m >> r), where 1/z spherical
        // spreading dominates.
        let amp_near_field = bowl.oneil_solution(0.05, peak_time(0.05)).abs();
        let amp_far_field = bowl.oneil_solution(0.20, peak_time(0.20)).abs();
        assert!(
            amp_near_field > amp_far_field,
            "Near-field amplitude ({amp_near_field:.3e}) must exceed far-field ({amp_far_field:.3e})"
        );

        // Temporal periodicity: P(t + T/2) = −P(t) at the focal point.
        let t0 = peak_time(focus_distance);
        let p_t0 = bowl.oneil_solution(focus_distance, t0);
        let p_t_half = bowl.oneil_solution(focus_distance, t0 + 1.0 / (2.0 * frequency));
        assert_relative_eq!(p_t0, -p_t_half, epsilon = 0.01 * expected_amplitude);
    }

    fn assert_close(actual: f64, expected: f64) {
        let tolerance = 64.0 * f64::EPSILON * expected.abs().max(1.0);
        assert!(
            (actual - expected).abs() <= tolerance,
            "actual {actual}, expected {expected}, tolerance {tolerance}"
        );
    }
}
