//! Transcranial brain FWI from a REAL head CT, with measurement data generated by
//! a full-wave forward simulation THROUGH the CT-derived medium, validated against
//! a co-registered MRI.
//!
//! Pipeline (no synthetic phantom; data is propagated through the CT medium):
//! ```text
//!   real CT (HU) ─► CT acoustic medium (skull+brain speed & density, water bath)
//!         │
//!         ├─► FDTD forward per source  ──►  receiver data d(r,t)
//!         │     (real waves propagate THROUGH the skull → genuine aberration,
//!         │      refraction, reflection in the data — NOT a Born projection)
//!         ▼
//!   masked FWI: skull frozen to the KNOWN CT value, brain reconstructed
//!         ▼
//!   reconstructed brain sound-speed image
//!         │  validate (independent)
//!   real MRI (T1) ─affine-resample to CT grid─► anatomical reference
//!         └── Pearson(reconstruction, MRI) over the brain
//! ```
//!
//! Roles: the **CT is the acoustic model** the ultrasound propagates through and is
//! reconstructed from. Measurement data is the FDTD forward map of that medium —
//! every shot is a real wave solve through the skull, so the inverse problem is not
//! a self-projection (no inverse crime in the data: the inversion starts from a flat
//! brain and must recover the contrast from waves that crossed the skull). The
//! **MRI is an independent ground-truth reference** used only to validate the
//! reconstruction; it never enters the forward model.
//!
//! # Data
//!
//! Defaults to the bundled RIRE patient 109 sample (real head CT + co-registered T1
//! MR): `data/cfb_gbm_sample/{ct,t1}.nii.gz`. Override with `KWAVERS_CT_PATH` /
//! `KWAVERS_MRI_PATH`. The `.nii.gz` files are not tracked by git; if absent, the
//! example prints instructions and exits.
//!
//! Run: `cargo run --release --example transcranial_ct_mri_reconstruction`
//!
//! References:
//! - West J. et al. (1997). RIRE intermodality registration. JCAT 21(4).
//! - Guasch L. et al. (2020). Full-waveform inversion for brain imaging. npj Digit. Med. 3, 28.
//! - Schneider U. et al. (1996). HU→density/speed. Phys. Med. Biol. 41(1).

use kwavers_core::error::KwaversResult;

fn main() -> KwaversResult<()> {
    run()
}

mod fwi_demo {
    use kwavers_core::constants::hu_mapping::HuAcousticModel;
    use kwavers_core::error::KwaversResult;
    use kwavers_diagnostics::reconstruction::transcranial_ust::{
        resample_head_slice, select_head_slice, AcousticSlice,
    };
    use kwavers_grid::Grid;
    use kwavers_math::statistics::pearson;
    use kwavers_solver::inverse::fwi::time_domain::{FwiGeometry, FwiProcessor};
    use kwavers_solver::inverse::seismic::parameters::{FwiParameters, RegularizationParameters};
    use kwavers_source::{GridSource, SourceMode};
    use leto::{Array2, Array3};
    use std::f64::consts::PI;
    use std::path::PathBuf;
    use std::time::Instant;

    // Resolution/budget. The skull (c≈2900 m/s) forces a small CFL timestep, so the
    // domain and shot/iteration counts are kept modest; the same code path scales by
    // raising these constants.
    // Acquisition/budget. Transcranial FWI is expensive: the skull (c≈2900 m/s)
    // forces a small CFL timestep, and CPML-FDTD (required for accuracy through the
    // strong skull contrast) does not have a fast self-adjoint shortcut here. The
    // defaults below run in ~30–40 min on CPU and recover the brain contrast; lower
    // them (or raise for a sharper image) — the result scales with N_SRC and ITERS.
    const GRID: usize = 40; // CT head slice resampled to GRID×GRID
    const PAD: usize = 8; // water-bath border (CPML-absorbed); sources sit here
    const N_SRC: usize = 16; // ring transmit/receive elements (coverage: N·(N−1) data)
    const ITERS: usize = 6; // masked-FWI iterations
    const F0_HZ: f64 = 150_000.0;
    const P0_PA: f64 = 1.0e5;
    const C_WATER: f64 = 1500.0;
    const RHO_WATER: f64 = 1000.0;
    const C_BRAIN_FLAT: f64 = 1540.0; // homogeneous brain start
    const C_BRAIN_MIN: f64 = 1480.0;
    const C_BRAIN_MAX: f64 = 1620.0;

    pub fn run() -> KwaversResult<()> {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .map(PathBuf::from)
            .unwrap_or_default();
        let ct_path = std::env::var("KWAVERS_CT_PATH").unwrap_or_else(|_| {
            root.join("data/cfb_gbm_sample/ct.nii.gz")
                .display()
                .to_string()
        });
        let mri_path = std::env::var("KWAVERS_MRI_PATH").unwrap_or_else(|_| {
            root.join("data/cfb_gbm_sample/t1.nii.gz")
                .display()
                .to_string()
        });

        let Some(ct) = load_nifti(&ct_path) else {
            println!(
                "Could not read CT NIfTI at {ct_path}.\n\
                 Place a real head CT there or set KWAVERS_CT_PATH. No synthetic fallback is used."
            );
            return Ok(());
        };
        println!(
            "Loaded CT {:?} spacing {:.3}×{:.3}×{:.3} mm  HU [{:.0}, {:.0}]",
            ct.data.shape(),
            ct.spacing_mm[0],
            ct.spacing_mm[1],
            ct.spacing_mm[2],
            ct.data.iter().copied().fold(f64::INFINITY, f64::min),
            ct.data.iter().copied().fold(f64::NEG_INFINITY, f64::max),
        );

        // ── CT head slice → 2-D acoustic fields ──────────────────────────────
        let slice_index = select_head_slice(&ct.data)?;
        let ct_slice = resample_head_slice(&ct.data, ct.spacing_mm, slice_index, GRID)?;
        let acoustic = AcousticSlice::from_ct_hu(ct_slice.hu.clone(), ct_slice.spacing_m)?;
        let dx = ct_slice.spacing_m;
        println!(
            "Slice {slice_index} resampled to {GRID}×{GRID} @ {:.2} mm",
            dx * 1.0e3
        );

        // ── Embed the head in a water bath: (N,N,2) FWI slab ─────────────────
        // The time-domain solver requires ≥2 points per axis; a 2-thick z-slab is
        // the standard quasi-2-D embedding (cf. brain_theranostic_monitor).
        let n = GRID + 2 * PAD;
        let grid = Grid::new(n, n, 2, dx, dx, dx)?;
        let hu_model = HuAcousticModel::default();
        let mut true_c = Array3::from_elem((n, n, 2), C_WATER);
        let mut density = Array3::from_elem((n, n, 2), RHO_WATER);
        let mut brain = Array3::from_elem((n, n, 2), false);
        // frozen = everything the inversion treats as KNOWN (skull, scalp, water);
        // only the brain is free. Built as the complement of the brain mask.
        for gi in 0..GRID {
            for gj in 0..GRID {
                let (fi, fj) = (gi + PAD, gj + PAD);
                let hu = ct_slice.hu[[gi, gj]];
                let is_tissue = hu > -200.0; // exclude air; keep scalp/skull/brain
                for k in 0..2 {
                    if is_tissue {
                        true_c[[fi, fj, k]] = acoustic.sound_speed_m_s[[gi, gj]];
                        density[[fi, fj, k]] = hu_model.density(hu);
                    }
                    brain[[fi, fj, k]] = acoustic.brain_mask[[gi, gj]];
                }
            }
        }
        let frozen: Array3<bool> = brain.mapv(|b| !b);
        let brain_voxels = brain.iter().filter(|b| **b).count();
        let c_hi = true_c.iter().copied().fold(0.0_f64, f64::max);

        // Inversion start: known medium with the brain flattened to a constant.
        let mut initial = true_c.clone();
        let mut reference = true_c.clone();
        for ([i, j, k], &is_brain) in brain.indexed_iter() {
            if is_brain {
                initial[[i, j, k]] = C_BRAIN_FLAT;
            }
        }
        // Reference brain values are never read (brain is free) but keep them sane.
        reference.assign(&true_c);

        // ── Ring transmit/receive elements in the water bath ─────────────────
        let center = (n as f64 - 1.0) / 2.0;
        let r_ring = GRID as f64 * 0.62; // clears the ~0.46·GRID skull, sits in water
        let mut elems: Vec<(usize, usize, usize)> = Vec::new();
        for s in 0..N_SRC {
            let theta = std::f64::consts::TAU * s as f64 / N_SRC as f64;
            let i = (center + r_ring * theta.cos()).round() as i64;
            let j = (center + r_ring * theta.sin()).round() as i64;
            if i > 2 && j > 2 && (i as usize) < n - 3 && (j as usize) < n - 3 {
                let (i, j) = (i as usize, j as usize);
                // Accept only genuine water voxels (outside the head).
                if (true_c[[i, j, 0]] - C_WATER).abs() < 1.0 {
                    elems.push((i, j, 0));
                }
            }
        }
        if elems.len() < 3 {
            println!("Could not place ≥3 ring elements in water — increase PAD/r_ring.");
            return Ok(());
        }

        // ── Time stepping (CFL set by the fast skull) ────────────────────────
        let dt = 0.3 * dx / (c_hi * 3.0_f64.sqrt());
        let transit = n as f64 * dx / C_WATER;
        let nt = ((transit * 1.3) / dt).ceil() as usize;
        println!(
            "FWI grid {n}×{n}×2; {} ring elements; nt={nt}, dt={dt:.2e}s; brain voxels {brain_voxels}; c_max {c_hi:.0} m/s",
            elems.len()
        );

        // ── Generate data by FDTD forward THROUGH the CT medium ──────────────
        let params = FwiParameters {
            max_iterations: ITERS,
            tolerance: 1e-12,
            step_size: 40.0,
            frequency: F0_HZ,
            nt,
            dt,
            n_trace: elems.len(),
            n_depth: 1,
            regularization: RegularizationParameters {
                tikhonov_weight: 0.0,
                tv_weight: 2.0e-4,
                directional_tv_weight: 0.0,
                directional_tv_adaptive: false,
                smoothness_weight: 0.0,
            },
            source_mute_radius: 4,
            ..FwiParameters::default()
        };
        // CPML-FDTD forward/adjoint (default engine). Required for accuracy through
        // the strong skull contrast: the faster lossless self-adjoint engine assumes
        // κ≈1 and is inaccurate for the c≈2900 m/s skull (it anti-correlates here).
        let fwi = FwiProcessor::new(params).with_density(density.clone())?;

        println!(
            "Generating {} shots (FDTD forward through the CT medium) …",
            elems.len()
        );
        let t_fwd = Instant::now();
        let mut shots: Vec<(FwiGeometry, Array2<f64>)> = Vec::new();
        for &src in &elems {
            let geom = build_shot(src, &elems, (n, n, 2), nt, dt);
            let obs = fwi.generate_synthetic_data(&true_c, &geom, &grid)?;
            shots.push((geom, obs));
        }
        println!(
            "  forward data generated in {:.1} s",
            t_fwd.elapsed().as_secs_f64()
        );

        // ── Masked FWI: skull/water frozen, brain reconstructed ──────────────
        println!("Running masked FWI ({ITERS} iters; skull frozen to CT) …");
        let t_inv = Instant::now();
        let recon = fwi.invert_multi_source_masked(
            &shots,
            &initial,
            &reference,
            &frozen,
            C_BRAIN_MIN,
            C_BRAIN_MAX,
            &grid,
        )?;
        println!("  inversion done in {:.1} s", t_inv.elapsed().as_secs_f64());

        // ── Reconstruction fidelity vs the CT-true brain (k=0 plane) ─────────
        let (mut r_brain, mut t_brain) = (Vec::new(), Vec::new());
        for gi in 0..GRID {
            for gj in 0..GRID {
                if acoustic.brain_mask[[gi, gj]] {
                    r_brain.push(recon[[gi + PAD, gj + PAD, 0]]);
                    t_brain.push(true_c[[gi + PAD, gj + PAD, 0]]);
                }
            }
        }
        let fidelity = pearson(&r_brain, &t_brain);
        let dyn_range = |v: &[f64]| {
            let lo = v.iter().copied().fold(f64::INFINITY, f64::min);
            let hi = v.iter().copied().fold(f64::NEG_INFINITY, f64::max);
            hi - lo
        };
        println!("\n── reconstruction ──");
        println!("  brain voxels reconstructed : {}", r_brain.len());
        println!(
            "  recon ↔ CT-true brain : Pearson {fidelity:+.3}  (FWI fidelity through the skull)"
        );
        println!(
            "  CT-true Δc {:.1} m/s | recon Δc {:.1} m/s",
            dyn_range(&t_brain),
            dyn_range(&r_brain)
        );

        // ── Independent validation against the registered MRI ────────────────
        let mri_grid = match load_nifti(&mri_path) {
            Some(mri) => {
                let (mri_slice, coverage) =
                    resample_mri_to_ct_grid(&ct, &mri, &ct_slice, slice_index);
                println!(
                    "\n── validation vs MRI {:?} (in-bounds coverage {:.0}%) ──",
                    mri.data.shape(),
                    coverage * 100.0
                );
                if coverage < 0.5 {
                    println!("  WARNING: low MRI↔CT coverage — affines may not be co-registered.");
                }
                let (mut rv, mut tv, mut mv) = (Vec::new(), Vec::new(), Vec::new());
                for gi in 0..GRID {
                    for gj in 0..GRID {
                        if acoustic.brain_mask[[gi, gj]] {
                            rv.push(recon[[gi + PAD, gj + PAD, 0]]);
                            tv.push(true_c[[gi + PAD, gj + PAD, 0]]);
                            mv.push(mri_slice[[gi, gj]]);
                        }
                    }
                }
                println!(
                    "  FWI reconstruction ↔ MRI anatomy : Pearson {:+.3}",
                    pearson(&rv, &mv)
                );
                println!(
                    "  CT model           ↔ MRI anatomy : Pearson {:+.3}  (reference)",
                    pearson(&tv, &mv)
                );
                println!(
                    "  Interpretation: data propagated through the real skull; the FWI recovers \
                     the CT brain contrast through the known skull. Agreement with independent MRI \
                     anatomy reflects how much true soft-tissue structure CT/US can resolve — CT \
                     brain contrast is weak, so the MRI-visible detail is the expected gap."
                );
                Some(mri_slice)
            }
            None => {
                println!("\nNo MRI at {mri_path} (set KWAVERS_MRI_PATH) — skipping validation.");
                None
            }
        };

        // ── Figures (PGM: dev-dep `image` carries no PNG encoder) ────────────
        let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("test-figures");
        std::fs::create_dir_all(&out_dir)?;
        save_pgm(
            &out_dir.join("transcranial_ct_true_speed.pgm"),
            &slice_xy(&true_c),
        )?;
        save_pgm(
            &out_dir.join("transcranial_fwi_reconstruction.pgm"),
            &slice_xy(&recon),
        )?;
        if let Some(mri_slice) = mri_grid {
            save_pgm(&out_dir.join("transcranial_mri_reference.pgm"), &mri_slice)?;
        }
        println!("\nFigures (PGM) written to {}", out_dir.display());
        Ok(())
    }

    /// Build a single-source FWI shot (one transmit voxel + receiver mask).
    fn build_shot(
        src: (usize, usize, usize),
        elems: &[(usize, usize, usize)],
        dims: (usize, usize, usize),
        nt: usize,
        dt: f64,
    ) -> FwiGeometry {
        let mut p_mask = Array3::<f64>::zeros(dims);
        p_mask[[src.0, src.1, src.2]] = 1.0;
        let wavelet = ricker(F0_HZ, dt, nt);
        let mut p_signal = Array2::<f64>::zeros((1, nt));
        for t in 0..nt {
            p_signal[[0, t]] = wavelet[t];
        }
        let mut source = GridSource::new_empty();
        source.p_mask = Some(p_mask);
        source.p_signal = Some(p_signal);
        source.p_mode = SourceMode::Dirichlet;

        let mut recv = Array3::<bool>::from_elem(dims, false);
        for &e in elems {
            if e != src {
                recv[[e.0, e.1, e.2]] = true;
            }
        }
        FwiGeometry::new(source, recv)
    }

    /// Ricker wavelet scaled to peak pressure `P0_PA`.
    fn ricker(f0: f64, dt: f64, nt: usize) -> Vec<f64> {
        let t_peak = 1.5 / f0;
        (0..nt)
            .map(|i| {
                let tau = PI * f0 * (i as f64 * dt - t_peak);
                P0_PA * (1.0 - 2.0 * tau * tau) * (-tau * tau).exp()
            })
            .collect()
    }

    /// Extract the z=0 plane of a `(n,n,1)` field as a 2-D array.
    fn slice_xy(v: &Array3<f64>) -> Array2<f64> {
        let [nx, ny, _] = v.shape();
        let mut out = Array2::zeros((nx, ny));
        for i in 0..nx {
            for j in 0..ny {
                out[[i, j]] = v[[i, j, 0]];
            }
        }
        out
    }

    // ── NIfTI I/O + affine MRI→CT resampling (validation only) ───────────────

    struct NiftiVolume {
        data: Array3<f64>,
        spacing_mm: [f64; 3],
        affine: [[f64; 4]; 4],
    }

    fn load_nifti(path: &str) -> Option<NiftiVolume> {
        use ritk_io::domain::ImageReader;
        use ritk_io::format::nifti::native::NiftiReader;

        let reader = NiftiReader::new(coeus_core::SequentialBackend);
        let obj = reader.read(path).ok()?;
        let shape = obj.shape();
        let spacing = obj.spacing();
        let origin = obj.origin();
        let direction = obj.direction();
        let spacing_mm = [spacing[0], spacing[1], spacing[2]];
        let affine = std::array::from_fn(|row| {
            std::array::from_fn(|column| {
                if column < 3 {
                    direction[(row, column)] * spacing[column]
                } else {
                    origin[row]
                }
            })
        });

        let flat_f64 = obj.data_vec().into_iter().map(f64::from).collect();
        let leto_array = leto::Array3::from_shape_vec(shape, flat_f64).ok()?;

        Some(NiftiVolume {
            data: leto_array,
            spacing_mm,
            affine,
        })
    }

    fn resample_mri_to_ct_grid(
        ct: &NiftiVolume,
        mri: &NiftiVolume,
        ct_slice: &kwavers_diagnostics::reconstruction::transcranial_ust::CtResampledSlice,
        slice_index: usize,
    ) -> (Array2<f64>, f64) {
        use kwavers_math::numerics::operators::interpolation::trilinear_index_space;
        let [grid, _] = ct_slice.hu.shape();
        let [x0, x1, y0, y1] = ct_slice.crop_bounds_index;
        let scale_x = if grid > 1 {
            (x1 - x0) as f64 / (grid - 1) as f64
        } else {
            0.0
        };
        let scale_y = if grid > 1 {
            (y1 - y0) as f64 / (grid - 1) as f64
        } else {
            0.0
        };
        let mri_inv = invert_affine(&mri.affine);
        let [mnx, mny, mnz] = mri.data.shape();
        let mut out = Array2::<f64>::zeros((grid, grid));
        let mut in_bounds = 0usize;
        for ix in 0..grid {
            let src_x = x0 as f64 + ix as f64 * scale_x;
            for iy in 0..grid {
                let src_y = y0 as f64 + iy as f64 * scale_y;
                let (wx, wy, wz) = apply_affine(&ct.affine, src_x, src_y, slice_index as f64);
                let (mx, my, mz) = apply_affine(&mri_inv, wx, wy, wz);
                if mx >= 0.0
                    && my >= 0.0
                    && mz >= 0.0
                    && mx <= (mnx - 1) as f64
                    && my <= (mny - 1) as f64
                    && mz <= (mnz - 1) as f64
                {
                    in_bounds += 1;
                    out[[ix, iy]] = trilinear_index_space(&mri.data, mx, my, mz);
                }
            }
        }
        (out, in_bounds as f64 / (grid * grid) as f64)
    }

    fn apply_affine(a: &[[f64; 4]; 4], x: f64, y: f64, z: f64) -> (f64, f64, f64) {
        (
            a[0][0] * x + a[0][1] * y + a[0][2] * z + a[0][3],
            a[1][0] * x + a[1][1] * y + a[1][2] * z + a[1][3],
            a[2][0] * x + a[2][1] * y + a[2][2] * z + a[2][3],
        )
    }

    /// Invert a NIfTI voxel→world affine `[[R|t],[0 0 0 1]]` → `[[R⁻¹|−R⁻¹t],[0 0 0 1]]`.
    fn invert_affine(a: &[[f64; 4]; 4]) -> [[f64; 4]; 4] {
        let m = [
            [a[0][0], a[0][1], a[0][2]],
            [a[1][0], a[1][1], a[1][2]],
            [a[2][0], a[2][1], a[2][2]],
        ];
        let det = m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1])
            - m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0])
            + m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0]);
        if det.abs() < 1.0e-30 {
            return [
                [1.0, 0.0, 0.0, 0.0],
                [0.0, 1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0, 0.0],
                [0.0, 0.0, 0.0, 1.0],
            ];
        }
        let id = 1.0 / det;
        let r = [
            [
                (m[1][1] * m[2][2] - m[1][2] * m[2][1]) * id,
                (m[0][2] * m[2][1] - m[0][1] * m[2][2]) * id,
                (m[0][1] * m[1][2] - m[0][2] * m[1][1]) * id,
            ],
            [
                (m[1][2] * m[2][0] - m[1][0] * m[2][2]) * id,
                (m[0][0] * m[2][2] - m[0][2] * m[2][0]) * id,
                (m[0][2] * m[1][0] - m[0][0] * m[1][2]) * id,
            ],
            [
                (m[1][0] * m[2][1] - m[1][1] * m[2][0]) * id,
                (m[0][1] * m[2][0] - m[0][0] * m[2][1]) * id,
                (m[0][0] * m[1][1] - m[0][1] * m[1][0]) * id,
            ],
        ];
        let t = [a[0][3], a[1][3], a[2][3]];
        let nt = [
            -(r[0][0] * t[0] + r[0][1] * t[1] + r[0][2] * t[2]),
            -(r[1][0] * t[0] + r[1][1] * t[1] + r[1][2] * t[2]),
            -(r[2][0] * t[0] + r[2][1] * t[1] + r[2][2] * t[2]),
        ];
        [
            [r[0][0], r[0][1], r[0][2], nt[0]],
            [r[1][0], r[1][1], r[1][2], nt[1]],
            [r[2][0], r[2][1], r[2][2], nt[2]],
            [0.0, 0.0, 0.0, 1.0],
        ]
    }

    /// Write a normalized 8-bit grayscale PGM (P5) — min→black, max→white.
    fn save_pgm(path: &std::path::Path, field: &Array2<f64>) -> std::io::Result<()> {
        use std::io::Write;
        let [nx, ny] = field.shape();
        let lo = field.iter().copied().fold(f64::INFINITY, f64::min);
        let hi = field.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        let span = (hi - lo).max(1.0e-12);
        let mut buf = Vec::with_capacity(nx * ny + 32);
        write!(buf, "P5\n{nx} {ny}\n255\n")?;
        for iy in 0..ny {
            for ix in 0..nx {
                buf.push(((field[[ix, iy]] - lo) / span * 255.0).clamp(0.0, 255.0) as u8);
            }
        }
        std::fs::write(path, &buf)
    }
}

fn run() -> KwaversResult<()> {
    fwi_demo::run()
}
