use super::*;
use crate::core::constants::fundamental::SOUND_SPEED_WATER_SIM;
use crate::domain::grid::Grid;

#[test]
fn test_wavenumber_computation() {
    let grid = Grid::new(8, 8, 8, 0.001, 0.001, 0.001).expect("Failed to create test grid");
    let (kx, ky, kz) = compute_wavenumbers(&grid);

    // Check dimensions
    assert_eq!(kx.dim(), (8, 8, 8));
    assert_eq!(ky.dim(), (8, 8, 8));
    assert_eq!(kz.dim(), (8, 8, 8));

    // Check DC component
    assert_eq!(kx[[0, 0, 0]], 0.0);
    assert_eq!(ky[[0, 0, 0]], 0.0);
    assert_eq!(kz[[0, 0, 0]], 0.0);

    // Check symmetry
    assert!((kx[[1, 0, 0]] + kx[[7, 0, 0]]).abs() < 1e-10);
}

/// Verify k-magnitude consistency between compute_k_magnitude and compute_k_squared.
///
/// Invariant: ‖k‖₂ = √(kx² + ky² + kz²) must satisfy ‖k‖₂² = k_squared element-wise.
#[test]
fn test_k_magnitude_squared_consistency() {
    let grid = Grid::new(8, 8, 8, 1e-3, 1e-3, 1e-3).expect("grid creation");
    let (kx, ky, kz) = compute_wavenumbers(&grid);

    let k_sq = compute_k_squared(&kx, &ky, &kz);
    let k_mag = compute_k_magnitude(&kx, &ky, &kz);

    // For every element: k_mag² must equal k_squared within f64 epsilon
    for ((km, ks), _) in k_mag.iter().zip(k_sq.iter()).zip(kx.iter()) {
        let diff = (km * km - ks).abs();
        assert!(
            diff < 1e-20,
            "k_mag²={} ≠ k_sq={} (diff={})",
            km * km,
            ks,
            diff
        );
    }
}

/// Verify spectral gradient via known analytical derivative.
///
/// For f(x) = sin(2π·x/L) on [0, L), the derivative is 2π/L · cos(2π·x/L).
/// This checks gradient_x to within numerical precision.
#[test]
fn test_spectral_gradient_x_sinusoid() {
    use std::f64::consts::PI;
    let n = 16_usize;
    let dx = 1e-3_f64;
    let grid = Grid::new(n, 1, 1, dx, dx, dx).expect("grid creation");

    let l = n as f64 * dx;
    let k_fund = 2.0 * PI / l;

    let mut field = ndarray::Array3::<f64>::zeros((n, 1, 1));
    for i in 0..n {
        field[[i, 0, 0]] = (k_fund * i as f64 * dx).sin();
    }
    let expected_deriv: Vec<f64> = (0..n)
        .map(|i| k_fund * (k_fund * i as f64 * dx).cos())
        .collect();

    let grad = gradient_x(&field, &grid).expect("gradient_x");
    for i in 0..n {
        let diff = (grad[[i, 0, 0]] - expected_deriv[i]).abs();
        assert!(
            diff < 1e-9,
            "i={i}: grad={}, expected={}, diff={diff}",
            grad[[i, 0, 0]],
            expected_deriv[i]
        );
    }
}

/// Canonical κ is generated by generate_kappa in math::fft::shift_operators.
/// Verify that compute_wavenumbers + compute_k_magnitude + the canonical sinc formula
/// matches generate_kappa output element-wise.
#[test]
fn test_canonical_kappa_matches_wavenumber_magnitude() {
    use crate::math::fft::shift_operators::generate_kappa;
    use std::f64::consts::PI;

    let c0 = SOUND_SPEED_WATER_SIM;
    let dx = 1e-3_f64;
    let cfl = 0.3_f64;
    let dt = cfl * dx / c0;
    let n = 16_usize;

    let kappa = generate_kappa(n, n, n, dx, dx, dx, c0, dt);

    let grid = Grid::new(n, n, n, dx, dx, dx).expect("grid creation");
    let (kx, ky, kz) = compute_wavenumbers(&grid);
    let k_mag = compute_k_magnitude(&kx, &ky, &kz);

    // κ(k) = sinc_unnorm(c0·|k|·dt/2) = sin(x)/x, x = c0·|k|·dt/2
    for ((km, kval), _) in kappa.iter().zip(k_mag.iter()).zip(kx.iter()) {
        let arg = c0 * kval * dt / 2.0;
        let expected = if arg.abs() < 1e-12 {
            1.0
        } else {
            arg.sin() / arg
        };
        let diff = (km - expected).abs();
        assert!(
            diff < 1e-12,
            "kappa={km}, expected={expected}, diff={diff}, k_mag={kval}, arg={arg}"
        );
    }
    // DC must equal 1.0
    assert!((kappa[[0, 0, 0]] - 1.0).abs() < 1e-12);
    // All values ∈ (-1, 1] for stable CFL
    assert!(kappa.iter().all(|&v| v > -1.0 && v <= 1.0 + 1e-12));
    // Positive at all k for CFL=0.3 (arg_max < π/2)
    let k_nyquist = PI / dx;
    let arg_max = c0 * k_nyquist * (3_f64).sqrt() * dt / 2.0; // √3 corner
    assert!(arg_max < PI / 2.0, "CFL=0.3 must keep arg_max < π/2");
    assert!(kappa.iter().all(|&v| v > 0.0));
}
