//! Dimensional algebra over the SI newtypes: same-unit sum/diff and scalar scaling (generated by
//! the two `macro_rules!` below), plus the hand-written cross-unit products that are dimensionally
//! valid — Ohm's law (`Ω·A = V`), power (`V·A = W`), charge (`F·V = C`), and their inverses.
//! Arithmetic that would silently mix dimensions is simply not implemented, so the compiler rejects
//! it.

use std::marker::PhantomData;
use std::ops::{Add, Div, Mul, Sub};

use super::kinds::{Amp, Celsius, Coulomb, Farad, Henry, Hz, Kelvin, Ohm, Volt, Watt};
use super::quantity::Float;

// ── Same-unit sum / difference ──────────────────────────────────────────────────────────────────

macro_rules! impl_same_unit_arith {
    ($($ty:ty),*) => {$(
        impl Add for $ty {
            type Output = $ty;
            fn add(self, rhs: $ty) -> $ty { Float(self.0 + rhs.0, std::marker::PhantomData) }
        }
        impl Sub for $ty {
            type Output = $ty;
            fn sub(self, rhs: $ty) -> $ty { Float(self.0 - rhs.0, std::marker::PhantomData) }
        }
    )*};
}

impl_same_unit_arith!(Hz, Ohm, Watt, Kelvin, Celsius, Volt, Amp, Henry, Farad, Coulomb);

// ── Scalar scaling × scalar divisions ───────────────────────────────────────────────────────────

macro_rules! impl_scalar_mul_div {
    ($($ty:ty),*) => {$(
        impl Mul<f64> for $ty {
            type Output = $ty;
            fn mul(self, rhs: f64) -> $ty { Float(self.0 * rhs, std::marker::PhantomData) }
        }
        impl Mul<$ty> for f64 {
            type Output = $ty;
            fn mul(self, rhs: $ty) -> $ty { Float(self * rhs.0, std::marker::PhantomData) }
        }
        impl Div<f64> for $ty {
            type Output = $ty;
            fn div(self, rhs: f64) -> $ty { Float(self.0 / rhs, std::marker::PhantomData) }
        }
        impl Div<$ty> for $ty {
            type Output = f64;
            fn div(self, rhs: $ty) -> f64 { self.0 / rhs.0 }
        }
    )*};
}

impl_scalar_mul_div!(Hz, Ohm, Watt, Kelvin, Celsius, Volt, Amp, Henry, Farad, Coulomb);

// ── Cross-unit products (dimensionally valid only) ──────────────────────────────────────────────

// Ohm × Amp = Volt (Ohm's law: V = I · R)
impl Mul<Amp> for Ohm {
    type Output = Volt;
    fn mul(self, rhs: Amp) -> Volt {
        Float(self.0 * rhs.0, PhantomData)
    }
}

// Volt / Ohm = Amp (I = V / R)
impl Div<Ohm> for Volt {
    type Output = Amp;
    fn div(self, rhs: Ohm) -> Amp {
        Float(self.0 / rhs.0, PhantomData)
    }
}

// Volt / Amp = Ohm (R = V / I)
impl Div<Amp> for Volt {
    type Output = Ohm;
    fn div(self, rhs: Amp) -> Ohm {
        Float(self.0 / rhs.0, PhantomData)
    }
}

// Volt × Amp = Watt (P = V · I)
impl Mul<Amp> for Volt {
    type Output = Watt;
    fn mul(self, rhs: Amp) -> Watt {
        Float(self.0 * rhs.0, PhantomData)
    }
}

// Watt / Volt = Amp (I = P / V)
impl Div<Volt> for Watt {
    type Output = Amp;
    fn div(self, rhs: Volt) -> Amp {
        Float(self.0 / rhs.0, PhantomData)
    }
}

// Watt / Amp = Volt (V = P / I)
impl Div<Amp> for Watt {
    type Output = Volt;
    fn div(self, rhs: Amp) -> Volt {
        Float(self.0 / rhs.0, PhantomData)
    }
}

// Farad × Volt = Coulomb (Q = C · V)
impl Mul<Volt> for Farad {
    type Output = Coulomb;
    fn mul(self, rhs: Volt) -> Coulomb {
        Float(self.0 * rhs.0, PhantomData)
    }
}
