//! The static pulser-IC datasheet catalog. The table is a compile-time `static` slice — every
//! `PulserIc` field is const-constructible — so [`available_pulsers`] hands back `&'static [PulserIc]`
//! with **no per-call heap allocation** (was a `vec![…]` rebuilt on every call).

use super::pulser_ic::{PulserIc, StockStatus};

/// Available HV ultrasound pulser ICs with DigiKey-verified parametric data.
///
/// Returns a borrow of the compile-time catalog; callers iterate (`.iter()` / `for p in …`) or
/// index it without allocating.
#[must_use]
pub fn available_pulsers() -> &'static [PulserIc] {
    PULSERS
}

/// The DigiKey-verified pulser-IC catalog, fixed at compile time.
static PULSERS: &[PulserIc] = &[
    PulserIc {
        part_number: "HV7355K6-G",
        vendor: "Microchip",
        channels: 8,
        v_max_v: 150.0,
        i_max_a: 1.5,
        r_on_ohm: 8.0,
        r_on_disch_ohm: 6.0,
        n_levels: 3,
        tr_switch: false,
        beamforming_mem: None,
        f_max_mhz: 10.0,
        q_g_nc: 20.0,
        v_gate_v: 5.0,
        package: "QFN-56",
        package_size_mm: (8.0, 8.0),
        pitch_mm: 0.4,
        r_th_ja_k_per_w: 28.0,
        cost_per_ch_usd: 4.50,
        stock_status: StockStatus::Active,
        supplies: &[150.0, 5.0, 3.3],
        i_supply_per_ch_ma: 2.5,
        charge_recycling: false,
        pattern_memory: false,
    },
    PulserIc {
        part_number: "STHVUP32",
        vendor: "STMicroelectronics",
        channels: 32,
        v_max_v: 100.0,
        i_max_a: 1.8,
        r_on_ohm: 5.0,
        r_on_disch_ohm: 4.0,
        n_levels: 5,
        tr_switch: false,
        beamforming_mem: Some(32 * 1024),
        f_max_mhz: 15.0,
        q_g_nc: 35.0,
        v_gate_v: 3.3,
        package: "BGA-289",
        package_size_mm: (16.0, 16.0),
        pitch_mm: 0.5,
        r_th_ja_k_per_w: 18.0,
        cost_per_ch_usd: 3.20,
        stock_status: StockStatus::Active,
        supplies: &[100.0, -100.0, 3.3, 1.8],
        i_supply_per_ch_ma: 3.0,
        charge_recycling: true,
        pattern_memory: true,
    },
    PulserIc {
        part_number: "MAX14815",
        vendor: "Analog Devices",
        channels: 8,
        v_max_v: 200.0,
        i_max_a: 2.0,
        r_on_ohm: 4.5,
        r_on_disch_ohm: 3.5,
        n_levels: 5,
        tr_switch: true,
        beamforming_mem: Some(8 * 4096),
        f_max_mhz: 20.0,
        q_g_nc: 25.0,
        v_gate_v: 3.3,
        package: "WLP-81",
        package_size_mm: (5.5, 5.5),
        pitch_mm: 0.4,
        r_th_ja_k_per_w: 22.0,
        cost_per_ch_usd: 5.80,
        stock_status: StockStatus::Active,
        supplies: &[200.0, 3.3, 1.8],
        i_supply_per_ch_ma: 4.0,
        charge_recycling: true,
        pattern_memory: true,
    },
    PulserIc {
        part_number: "STHV748S",
        vendor: "STMicroelectronics",
        channels: 4,
        v_max_v: 90.0,
        i_max_a: 2.0,
        r_on_ohm: 3.5,
        r_on_disch_ohm: 2.5,
        n_levels: 3,
        tr_switch: false,
        beamforming_mem: None,
        f_max_mhz: 20.0,
        q_g_nc: 30.0,
        v_gate_v: 3.3,
        package: "QFN-48",
        package_size_mm: (7.0, 7.0),
        pitch_mm: 0.5,
        r_th_ja_k_per_w: 24.0,
        cost_per_ch_usd: 2.80,
        stock_status: StockStatus::Active,
        supplies: &[90.0, 3.3],
        i_supply_per_ch_ma: 3.0,
        charge_recycling: false,
        pattern_memory: false,
    },
    PulserIc {
        part_number: "MD1715",
        vendor: "Microchip",
        channels: 2,
        v_max_v: 200.0,
        i_max_a: 3.5,
        r_on_ohm: 0.5,
        r_on_disch_ohm: 0.5,
        n_levels: 5,
        tr_switch: false,
        beamforming_mem: None,
        f_max_mhz: 7.0,
        q_g_nc: 50.0,
        v_gate_v: 12.0,
        package: "QFN-28",
        package_size_mm: (5.0, 5.0),
        pitch_mm: 0.5,
        r_th_ja_k_per_w: 30.0,
        cost_per_ch_usd: 2.50,
        stock_status: StockStatus::Active,
        supplies: &[200.0, 12.0, 5.0],
        i_supply_per_ch_ma: 8.0,
        charge_recycling: true,
        pattern_memory: false,
    },
    PulserIc {
        part_number: "HV7360",
        vendor: "Microchip",
        channels: 1,
        v_max_v: 100.0,
        i_max_a: 2.5,
        r_on_ohm: 3.0,
        r_on_disch_ohm: 2.0,
        n_levels: 3,
        tr_switch: false,
        beamforming_mem: None,
        f_max_mhz: 20.0,
        q_g_nc: 15.0,
        v_gate_v: 5.0,
        package: "QFN-16",
        package_size_mm: (3.0, 3.0),
        pitch_mm: 0.5,
        r_th_ja_k_per_w: 40.0,
        cost_per_ch_usd: 4.00,
        stock_status: StockStatus::Active,
        supplies: &[100.0, 5.0],
        i_supply_per_ch_ma: 2.0,
        charge_recycling: false,
        pattern_memory: false,
    },
];
