#!/usr/bin/env python3
"""
Parity comparison for the vendored k-wave-python `at_array_as_source` example.

Mathematical specification
--------------------------
The upstream example builds three arc elements, applies a rigid planar affine
transform, and drives each element with a distinct tone-burst waveform.  The
physical comparison target is the propagated pressure field generated by the
distributed source matrix on the active grid points.

This comparison reports:

* binary source mask parity,
* weighted source mask parity,
* distributed source matrix parity after canonical active-point ordering,
* `p_max` field parity,
* `p_rms` field parity.
"""

from __future__ import annotations

import argparse
import os
import tempfile
import time
from pathlib import Path

import numpy as np

from example_parity_utils import DEFAULT_OUTPUT_DIR, bootstrap_example_paths, compute_image_metrics, save_text_report
from at_array_as_source_outputs import build_report_lines, save_comparison_figure


_ROOT = bootstrap_example_paths()

import pykwavers as pkw
from array_sensor_utils import ArcElementGeometry, build_arc_element_geometry
from array_source_utils import build_pykwavers_distributed_arc_signal
from kwave.data import Vector
from kwave.kgrid import kWaveGrid
from kwave.kmedium import kWaveMedium
from kwave.ksensor import kSensor
from kwave.ksource import kSource
from kwave.kspaceFirstOrder2D import kspaceFirstOrder2DC
from kwave.options.simulation_execution_options import SimulationExecutionOptions
from kwave.options.simulation_options import SimulationOptions
from kwave.utils.kwave_array import kWaveArray as KWaveArray_Kwave
from kwave.utils.signals import tone_burst


NX = 256
NY = 256
DX = 0.5e-3
DY = 0.5e-3
GRID_POINTS = Vector([NX, NY])
GRID_SPACING = Vector([DX, DY])

SOUND_SPEED = 1500.0
DENSITY = 1000.0
PML_SIZE = 20

ARC_RADIUS = 50e-3
ARC_DIAMETER = 30e-3
FOCUS_POSITION = np.array([-20e-3, 0.0], dtype=np.float64)
ARC_POSITIONS = (
    np.array([10e-3, -40e-3], dtype=np.float64),
    np.array([20e-3, 0.0], dtype=np.float64),
    np.array([10e-3, 40e-3], dtype=np.float64),
)

ARRAY_TRANSLATION = np.array([10e-3, 0.0], dtype=np.float64)
ARRAY_ROTATION_DEG = 10.0
DOMAIN_TRANSLATION = np.array([NX * DX / 2.0, NY * DY / 2.0], dtype=np.float64)

SOURCE_FREQUENCIES = (100e3, 200e3, 500e3)
SOURCE_CYCLES = (3, 5, 5)

FIGURE_PATH = DEFAULT_OUTPUT_DIR / "at_array_as_source_compare.png"
METRICS_PATH = DEFAULT_OUTPUT_DIR / "at_array_as_source_metrics.txt"
KWAVE_CACHE = DEFAULT_OUTPUT_DIR / "at_array_as_source_kwave_cache.npz"
PYKWAVERS_CACHE = DEFAULT_OUTPUT_DIR / "at_array_as_source_pykwavers_cache.npz"
CACHE_VERSION = 2
REFRESH_CACHE = os.getenv("KWAVERS_REFRESH_CACHE", "0") == "1"


def _apply_affine_2d(point: np.ndarray, translation: np.ndarray, rotation_deg: float) -> np.ndarray:
    """Apply the same 2D affine transform as k-wave-python's `set_array_position`."""
    point = np.asarray(point, dtype=np.float64).reshape(2)
    translation = np.asarray(translation, dtype=np.float64).reshape(2)
    theta = np.deg2rad(float(rotation_deg))
    rotation = np.array(
        [
            [np.cos(theta), -np.sin(theta)],
            [np.sin(theta), np.cos(theta)],
        ],
        dtype=np.float64,
    )
    return rotation @ point + translation


def _build_arc_geometries() -> list[ArcElementGeometry]:
    """Return the pykwavers arc geometries after the rigid array transform."""
    transformed_focus = _apply_affine_2d(FOCUS_POSITION, ARRAY_TRANSLATION, ARRAY_ROTATION_DEG)
    arc_geometries = []
    for arc_position in ARC_POSITIONS:
        transformed_arc = _apply_affine_2d(arc_position, ARRAY_TRANSLATION, ARRAY_ROTATION_DEG)
        arc_geometries.append(
            build_arc_element_geometry(
                transformed_arc,
                ARC_RADIUS,
                ARC_DIAMETER,
                transformed_focus,
                DOMAIN_TRANSLATION,
            )
        )
    return arc_geometries


def _build_source_signal_matrix(kgrid: kWaveGrid) -> np.ndarray:
    """Build the padded 3-row tone-burst source matrix used by the example."""
    nt = int(kgrid.Nt)
    signals = np.zeros((len(SOURCE_FREQUENCIES), nt), dtype=np.float64)
    for row, (frequency, cycles) in enumerate(zip(SOURCE_FREQUENCIES, SOURCE_CYCLES, strict=True)):
        burst = np.asarray(tone_burst(1.0 / float(kgrid.dt), frequency, cycles), dtype=np.float64).ravel()
        n = min(nt, burst.size)
        signals[row, :n] = burst[:n]
    return signals


def _build_kwave_array(arc_positions_kw: tuple[np.ndarray, ...]) -> KWaveArray_Kwave:
    """Build the reference k-wave-python array with the vendor affine transform."""
    array = KWaveArray_Kwave(bli_tolerance=0.05, upsampling_rate=10)
    for arc_position in arc_positions_kw:
        array.add_arc_element(arc_position.tolist(), ARC_RADIUS, ARC_DIAMETER, FOCUS_POSITION.tolist())
    array.set_array_position(ARRAY_TRANSLATION.tolist(), ARRAY_ROTATION_DEG)
    return array


def _load_cached_result(path: Path) -> dict[str, np.ndarray | float] | None:
    if REFRESH_CACHE or not path.exists():
        return None
    cached = np.load(path, allow_pickle=False)
    version = int(np.asarray(cached["cache_version"]).reshape(())) if "cache_version" in cached.files else 0
    if version != CACHE_VERSION:
        return None
    return {
        "p_max": np.asarray(cached["p_max"], dtype=np.float64),
        "p_rms": np.asarray(cached["p_rms"], dtype=np.float64),
        "source_binary_mask": np.asarray(cached["source_binary_mask"], dtype=bool),
        "source_weighted_mask": np.asarray(cached["source_weighted_mask"], dtype=np.float64),
        "distributed_signal": np.asarray(cached["distributed_signal"], dtype=np.float64),
        "runtime_s": float(cached["runtime_s"]),
        "dt": float(cached["dt"]),
        "time_steps": float(cached["time_steps"]),
    }


def run_kwave_reference() -> dict[str, np.ndarray | float]:
    """Run the vendored k-wave-python source example on the CPU backend."""
    cached = _load_cached_result(KWAVE_CACHE)
    if cached is not None:
        return cached

    kgrid = kWaveGrid(GRID_POINTS, GRID_SPACING)
    medium = kWaveMedium(sound_speed=SOUND_SPEED, density=DENSITY)
    kgrid.makeTime(medium.sound_speed)

    source_signal = _build_source_signal_matrix(kgrid)
    karray = _build_kwave_array(ARC_POSITIONS)
    source_binary_mask = np.squeeze(np.asarray(karray.get_array_binary_mask(kgrid), dtype=bool))
    source_weighted_mask = np.squeeze(np.asarray(karray.get_array_grid_weights(kgrid), dtype=np.float64))
    distributed_signal = np.asarray(karray.get_distributed_source_signal(kgrid, source_signal), dtype=np.float64)

    source = kSource()
    source.p_mask = source_binary_mask
    source.p = np.asarray(karray.get_distributed_source_signal(kgrid, source_signal), dtype=np.float64)

    sensor = kSensor()
    sensor.mask = np.ones((NX, NY), dtype=bool)
    sensor.record = ["p_max", "p_rms"]

    sim_options = SimulationOptions(
        pml_inside=True,
        pml_size=PML_SIZE,
        data_cast="single",
        save_to_disk=True,
        input_filename="at_array_as_source_kwave.h5",
        data_path=tempfile.gettempdir(),
    )
    exec_options = SimulationExecutionOptions(is_gpu_simulation=False, verbose_level=0, show_sim_log=False)

    start = time.perf_counter()
    sensor_data = kspaceFirstOrder2DC(
        medium=medium,
        kgrid=kgrid,
        source=source,
        sensor=sensor,
        simulation_options=sim_options,
        execution_options=exec_options,
    )
    runtime_s = time.perf_counter() - start

    output = {
        "p_max": np.asarray(sensor_data["p_max"], dtype=np.float64),
        "p_rms": np.asarray(sensor_data["p_rms"], dtype=np.float64),
        "source_binary_mask": source_binary_mask,
        "source_weighted_mask": source_weighted_mask,
        "distributed_signal": distributed_signal,
        "runtime_s": runtime_s,
        "dt": float(kgrid.dt),
        "time_steps": float(kgrid.Nt),
    }
    np.savez(KWAVE_CACHE, cache_version=CACHE_VERSION, **output)
    return output


def run_pykwavers_reference() -> dict[str, np.ndarray | float]:
    """Run the pykwavers source example with canonical active-point ordering."""
    cached = _load_cached_result(PYKWAVERS_CACHE)
    if cached is not None:
        return cached

    kgrid = kWaveGrid(GRID_POINTS, GRID_SPACING)
    medium = kWaveMedium(sound_speed=SOUND_SPEED, density=DENSITY)
    kgrid.makeTime(medium.sound_speed)

    arc_geometries = _build_arc_geometries()
    source_signal = _build_source_signal_matrix(kgrid)
    source_binary_mask, source_signal_matrix, element_weight_masks = build_pykwavers_distributed_arc_signal(
        arc_geometries,
        pkw.Grid(nx=NX, ny=NY, nz=1, dx=DX, dy=DY, dz=DX),
        source_signal,
    )
    source_weighted_mask = np.zeros_like(source_binary_mask, dtype=np.float64)
    for weight_mask in element_weight_masks:
        source_weighted_mask += weight_mask

    source = pkw.Source.from_mask(
        source_binary_mask[:, :, None].astype(np.float64),
        source_signal_matrix,
        SOURCE_FREQUENCIES[0],
        mode="additive",
    )
    sensor = pkw.Sensor.from_mask(np.ones((NX, NY, 1), dtype=bool))
    sensor.set_record(["p_max", "p_rms"])

    grid = pkw.Grid(nx=NX, ny=NY, nz=1, dx=DX, dy=DY, dz=DX)
    medium_pk = pkw.Medium.homogeneous(sound_speed=SOUND_SPEED, density=DENSITY)
    sim = pkw.Simulation(grid, medium_pk, source, sensor, solver=pkw.SolverType.PSTD)
    sim.set_pml_size(PML_SIZE)
    sim.set_pml_inside(True)

    start = time.perf_counter()
    result = sim.run(time_steps=int(kgrid.Nt), dt=float(kgrid.dt))
    runtime_s = time.perf_counter() - start

    output = {
        "p_max": np.asarray(result.p_max, dtype=np.float64).ravel(),
        "p_rms": np.asarray(result.p_rms, dtype=np.float64).ravel(),
        "source_binary_mask": source_binary_mask,
        "source_weighted_mask": source_weighted_mask,
        "distributed_signal": source_signal_matrix,
        "runtime_s": runtime_s,
        "dt": float(result.dt),
        "time_steps": float(result.time_steps),
    }
    np.savez(PYKWAVERS_CACHE, cache_version=CACHE_VERSION, **output)
    return output


def run_comparison() -> dict[str, object]:
    """Run the full comparison and return aligned arrays plus metrics."""
    kw = run_kwave_reference()
    py = run_pykwavers_reference()

    source_mask_metrics = compute_image_metrics(kw["source_binary_mask"], py["source_binary_mask"])
    source_weighted_metrics = compute_image_metrics(kw["source_weighted_mask"], py["source_weighted_mask"])
    source_signal_metrics = compute_image_metrics(kw["distributed_signal"], py["distributed_signal"])
    p_max_metrics = compute_image_metrics(kw["p_max"], py["p_max"])
    p_rms_metrics = compute_image_metrics(kw["p_rms"], py["p_rms"])

    return {
        "kwave": kw,
        "pykwavers": py,
        "metrics": {
            "source_mask": source_mask_metrics,
            "source_weighted_mask": source_weighted_metrics,
            "source_signal": source_signal_metrics,
            "p_max": p_max_metrics,
            "p_rms": p_rms_metrics,
        },
        "layout": {
            "source_binary_mask": np.asarray(kw["source_binary_mask"], dtype=bool),
            "source_weighted_mask": np.asarray(kw["source_weighted_mask"], dtype=np.float64),
            "source_signal_kw": np.asarray(kw["distributed_signal"], dtype=np.float64),
            "source_signal_py": np.asarray(py["distributed_signal"], dtype=np.float64),
        },
    }


PARITY_THRESHOLDS = {
    "source_mask": {
        "pearson_r": 0.999999,
    },
    "source_weighted_mask": {
        "pearson_r": 0.999999,
        "max_abs_diff": 1e-12,
    },
    "source_signal": {
        "pearson_r": 0.999999,
        "max_abs_diff": 1e-12,
    },
    "p_max": {
        "pearson_r": 0.98,
    },
    "p_rms": {
        "rms_ratio_min": 0.90,
        "rms_ratio_max": 1.10,
    },
}


def _metrics_pass(metrics: dict[str, dict[str, float]]) -> bool:
    """Return true when metrics satisfy the script-owned parity contract."""
    for metric_name, thresholds in PARITY_THRESHOLDS.items():
        metric = metrics[metric_name]
        if "pearson_r" in thresholds and metric["pearson_r"] < thresholds["pearson_r"]:
            return False
        if "max_abs_diff" in thresholds and metric["max_abs_diff"] >= thresholds["max_abs_diff"]:
            return False
        if "rms_ratio_min" in thresholds and metric["rms_ratio"] < thresholds["rms_ratio_min"]:
            return False
        if "rms_ratio_max" in thresholds and metric["rms_ratio"] > thresholds["rms_ratio_max"]:
            return False
        if "rmse" in thresholds and metric["rmse"] >= thresholds["rmse"]:
            return False
        if "psnr_db" in thresholds and metric["psnr_db"] <= thresholds["psnr_db"]:
            return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-cache", action="store_true", help="Ignore cached results and recompute both runs")
    parser.add_argument("--allow-failure", action="store_true")
    args = parser.parse_args()
    global REFRESH_CACHE
    if args.no_cache:
        REFRESH_CACHE = True

    result = run_comparison()
    metrics = result["metrics"]

    p_max_r = float(metrics["p_max"]["pearson_r"])
    p_rms_rms = float(metrics["p_rms"]["rms_ratio"])
    overall_status = "PASS" if _metrics_pass(metrics) else "FAIL"

    report_lines = build_report_lines(result)
    report_lines.append(f"parity_status: {overall_status}")
    save_comparison_figure(result, FIGURE_PATH)
    save_text_report(METRICS_PATH, "at_array_as_source parity report", report_lines)

    print("=" * 80)
    print("k-wave-python at_array_as_source vs pykwavers")
    print("=" * 80)
    print(
        "p_max Pearson r:   "
        f"{p_max_r:.6f}  (target >= {PARITY_THRESHOLDS['p_max']['pearson_r']})"
    )
    print(
        "p_rms RMS ratio:   "
        f"{p_rms_rms:.6f}  "
        f"(target [{PARITY_THRESHOLDS['p_rms']['rms_ratio_min']}, "
        f"{PARITY_THRESHOLDS['p_rms']['rms_ratio_max']}])"
    )
    print(f"Status:            {overall_status}")

    return 0 if overall_status == "PASS" or args.allow_failure else 1


if __name__ == "__main__":
    raise SystemExit(main())
