//! Forward model construction and execution.
//!
//! ## Solver-dispatch contract
//!
//! [`FwiProcessor::build_solver_for_forward`] is the single construction point
//! for both forward and adjoint passes.  It dispatches on
//! [`FwiParameters::solver_type`](crate::inverse::seismic::parameters::FwiParameters::solver_type)
//! and returns a fully configured `Box<dyn Solver>` — CPML (or equivalent
//! absorbing boundary) is applied **inside** this function before boxing so no
//! caller ever holds a concrete solver type.
//!
//! Supported variants:
//! - `SolverType::FDTD` — `FdtdSolver` with 2nd-order stencil + CPML (default).
//! - `SolverType::PSTD` — `PSTDSolver` with k-space spectral propagation;
//!   CPML is embedded in `PSTDConfig::boundary` at construction time so no
//!   separate `enable_cpml` call is needed.

use super::{geometry::FwiGeometry, FwiProcessor};
use kwavers_core::error::{KwaversError, KwaversResult, ValidationError};
use kwavers_domain::boundary::cpml::{CPMLConfig, PerDimensionPML};
use kwavers_grid::Grid;
use kwavers_medium::heterogeneous::HeterogeneousFactory;
use kwavers_domain::source::GridSource;
use crate::config::SolverType;
use crate::interface::Solver;
use ndarray::{s, Array2, Array3, Array4};

impl FwiProcessor {
    /// Generate receiver-time synthetic data for a model and acquisition geometry.
    ///
    /// # Theorem
    ///
    /// Returns the discrete forward map
    /// `F_h(c; G) = R_G p_h(c, q_G)`
    /// using the same discrete operator as [`Self::invert`].  Any synthetic
    /// data used by examples, tests, or callers is generated by the same
    /// operator as the FWI objective and gradient.
    /// # Errors
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub fn generate_synthetic_data(
        &self,
        model: &Array3<f64>,
        geometry: &FwiGeometry,
        grid: &Grid,
    ) -> KwaversResult<Array2<f64>> {
        geometry.validate(grid, self.parameters.nt)?;
        self.forward_model_sensor_only(model, geometry, grid)
    }

    /// Construct a fully configured solver ready for time-stepping.
    ///
    /// ## Single source of truth
    ///
    /// Both `forward_model` (full history) and `forward_model_sensor_only` (no
    /// history) require identical solver setup.  This helper centralises that
    /// setup so neither variant drifts from the other, and so the adjoint pass
    /// can build a matching solver through the same path.
    ///
    /// The returned `Box<dyn Solver>` is ready at `t = 0`.  CPML (or
    /// equivalent absorbing boundary) has already been applied before boxing;
    /// no caller needs to downcast to a concrete type.
    ///
    /// ## Returns
    /// `(Box<dyn Solver>, (nx, ny, nz), dt)` at t = 0 ready for `step_forward` calls.
    /// # Errors
    /// - Returns [`KwaversError::InvalidInput`] when `FwiParameters::solver_type`
    ///   is not yet supported by this builder.
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub(super) fn build_solver_for_forward(
        &self,
        model: &Array3<f64>,
        geometry: &FwiGeometry,
        grid: &Grid,
    ) -> KwaversResult<(Box<dyn Solver>, (usize, usize, usize), f64)> {
        geometry.validate(grid, self.parameters.nt)?;
        let dt = self.validate_time_step(model, grid)?;
        let (nx, ny, nz) = grid.dimensions();

        let solver: Box<dyn Solver> = match self.parameters.solver_type {
            SolverType::FDTD => self.build_fdtd_boxed(
                model,
                Some(geometry.sensor_mask.clone()),
                grid,
                dt,
                geometry.source.clone(),
            )?,
            SolverType::PSTD => self.build_pstd_boxed(
                model,
                Some(geometry.sensor_mask.clone()),
                grid,
                dt,
                geometry.source.clone(),
            )?,
            other => {
                return Err(KwaversError::InvalidInput(format!(
                    "FWI time-domain builder: SolverType::{other:?} is not yet supported; \
                     use FDTD or PSTD"
                )))
            }
        };
        Ok((solver, (nx, ny, nz), dt))
    }

    /// Build an FDTD solver (concrete) with CPML applied, then box.
    ///
    /// ## CPML
    /// σ_max = -(m+1)·ln(R_target)/(2·d·c_max), Roden & Gedney (2000).
    pub(super) fn build_fdtd_boxed(
        &self,
        model: &Array3<f64>,
        sensor_mask: Option<ndarray::Array3<bool>>,
        grid: &Grid,
        dt: f64,
        source: GridSource,
    ) -> KwaversResult<Box<dyn Solver>> {
        use crate::fdtd::{FdtdConfig, FdtdSolver, KSpaceCorrectionMode};

        let (_, ny, _) = grid.dimensions();
        let num_steps = self.parameters.nt;

        let config = FdtdConfig {
            spatial_order: 2,
            staggered_grid: true,
            cfl_factor: 0.3,
            subgridding: false,
            subgrid_factor: 2,
            enable_gpu_acceleration: false,
            enable_nonlinear: false,
            kspace_correction: KSpaceCorrectionMode::None,
            nt: num_steps,
            dt,
            sensor_mask,
            geometry: Default::default(),
        };

        let density = self.resolved_density(grid)?;
        let medium = HeterogeneousFactory::from_arrays(
            model.clone(),
            density,
            None,
            None, // alpha_power: default 1.0
            None,
            self.parameters.frequency,
        )
        .map_err(kwavers_core::error::KwaversError::InvalidInput)?;

        let mut solver = FdtdSolver::new(config, grid, &medium, source)?;

        let c_max = model.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        let y_pml = if ny > 20 { 10usize } else { 0usize };
        let cpml_config = CPMLConfig {
            thickness: 10,
            per_dimension: PerDimensionPML::new(10, y_pml, 10),
            ..CPMLConfig::default()
        };
        solver.enable_cpml(cpml_config, dt, c_max)?;

        Ok(Box::new(solver))
    }

    /// Build a PSTD solver (concrete) with CPML embedded in `PSTDConfig::boundary`, then box.
    ///
    /// ## CPML in PSTD
    ///
    /// `PSTDSolver::new` applies `CPMLBoundary::new_with_time_step` from the
    /// `BoundaryConfig::CPML` in the config.  The reference wave speed `c_ref`
    /// is derived internally from the medium, so no explicit `c_max` argument
    /// is required from this function.
    pub(super) fn build_pstd_boxed(
        &self,
        model: &Array3<f64>,
        sensor_mask: Option<ndarray::Array3<bool>>,
        grid: &Grid,
        dt: f64,
        source: GridSource,
    ) -> KwaversResult<Box<dyn Solver>> {
        use kwavers_physics::acoustics::mechanics::absorption::AbsorptionMode;
        use crate::forward::pstd::config::{BoundaryConfig, PSTDConfig};
        use crate::forward::pstd::implementation::core::orchestrator::PSTDSolver;

        let (_, ny, _) = grid.dimensions();
        let num_steps = self.parameters.nt;
        let y_pml = if ny > 20 { 10usize } else { 0usize };

        let cpml_config = CPMLConfig {
            thickness: 10,
            per_dimension: PerDimensionPML::new(10, y_pml, 10),
            ..CPMLConfig::default()
        };

        let config = PSTDConfig {
            nt: num_steps,
            dt,
            absorption_mode: AbsorptionMode::Lossless,
            nonlinearity: false,
            boundary: BoundaryConfig::CPML(cpml_config),
            sensor_mask,
            ..PSTDConfig::default()
        };

        let density = self.resolved_density(grid)?;
        let medium = HeterogeneousFactory::from_arrays(
            model.clone(),
            density,
            None,
            None, // alpha_power: default 1.0
            None,
            self.parameters.frequency,
        )
        .map_err(kwavers_core::error::KwaversError::InvalidInput)?;

        // PSTDSolver::new takes owned Grid; clone is required.
        let solver = PSTDSolver::new(config, grid.clone(), &medium, source)?;

        Ok(Box::new(solver))
    }

    /// Run the forward FDTD model and return both receiver traces and the full
    /// pressure-history volume needed by the adjoint pass.
    ///
    /// ## Memory contract
    ///
    /// Allocates `Array4<f64>` of shape `(nt, nx, ny, nz)` (≈ 3.3 GB for
    /// nt=2115, 64×48×64).  Do not call from `compute_objective` or any
    /// line-search path; use `forward_model_sensor_only` there.
    /// # Errors
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub(super) fn forward_model(
        &self,
        model: &Array3<f64>,
        geometry: &FwiGeometry,
        grid: &Grid,
    ) -> KwaversResult<(Array2<f64>, Array4<f64>)> {
        let (mut solver, (nx, ny, nz), _dt) =
            self.build_solver_for_forward(model, geometry, grid)?;

        let mut history = Array4::zeros((self.parameters.nt, nx, ny, nz));

        for t in 0..self.parameters.nt {
            // `solver` is `Box<dyn Solver>` — dynamic dispatch through the
            // unified Solver trait (T19a/T19b). No concrete-type path remains.
            solver.step_forward()?;
            history
                .slice_mut(s![t, .., .., ..])
                .assign(solver.pressure_field());
        }

        let recorded = solver.recorded_sensor_pressure().ok_or_else(|| {
            KwaversError::Validation(ValidationError::ConstraintViolation {
                message: "FWI forward model requires at least one receiver".to_owned(),
            })
        })?;
        let synthetic = recorded.slice(s![.., 0..self.parameters.nt]).to_owned();

        Ok((synthetic, history))
    }

    /// Run the forward FDTD model and return only receiver traces — no history.
    ///
    /// ## Theorem
    ///
    /// The L2 objective depends only on `d_syn(r,t)`, not on `p(x,t)`.  Storing
    /// `p(x,t)` is unnecessary for objective evaluation and prohibits safe
    /// shot-level parallelism in the line search.
    ///
    /// ## Memory contract
    ///
    /// Peak allocation per call: O(N_receivers × nt × 8 bytes) ≈ 5 MB.  Total
    /// per-call footprint ~55 MB; safe to run in parallel via `rayon::par_iter`.
    /// # Errors
    /// - Propagates any [`KwaversError`] returned by called functions.
    ///
    pub(super) fn forward_model_sensor_only(
        &self,
        model: &Array3<f64>,
        geometry: &FwiGeometry,
        grid: &Grid,
    ) -> KwaversResult<Array2<f64>> {
        let (mut solver, _dims, _dt) = self.build_solver_for_forward(model, geometry, grid)?;

        for _ in 0..self.parameters.nt {
            solver.step_forward()?;
        }

        let recorded = solver.recorded_sensor_pressure().ok_or_else(|| {
            KwaversError::Validation(ValidationError::ConstraintViolation {
                message: "FWI forward model requires at least one receiver".to_owned(),
            })
        })?;
        let synthetic = recorded.slice(s![.., 0..self.parameters.nt]).to_owned();

        Ok(synthetic)
    }
}
