"""Generate and check the ADR index at `docs/adr/README.md`.

The index already carried the header "Generated by scripts/adr-index.py -- do
not hand-edit". This is that script; it had never existed. In its absence the
index was hand-edited, which is what its header forbids, and two consequences
followed:

- every pull request adding an ADR conflicted with every other one on the same
  table, because two appended rows land on the same line;
- nothing detected two ADRs claiming the same number, so collisions surfaced
  only as a merge conflict during a rebase, one number at a time.

`generate` rebuilds the table from the files, so the conflict resolution is to
regenerate rather than to merge. `check` verifies the committed index matches
and that no number is claimed twice.

Usage:
    python scripts/adr-index.py generate
    python scripts/adr-index.py check
"""

from __future__ import annotations

import argparse
import io
import pathlib
import re
import sys

ADR_DIR = pathlib.Path("docs/adr")
INDEX = ADR_DIR / "README.md"

# The number comes from the filename, which is the one place every ADR agrees.
FILENAME = re.compile(r"^(\d+)-(.+)\.md$")

# Four heading shapes are in use across the 82 committed records:
#   `# ADR 119 — Title`   (the majority)
#   `# 124. Title`
#   `# ADR-035: Title`
#   `# Title`             (no number)
# The number is already known from the filename, so each prefix is stripped and
# whatever remains is the title.
# Only a top-level heading is a title. Two records open directly with a
# `## Status` section and carry no `#` line at all; taking their first `##`
# would title them "Context", so they fall back to their filename slug.
HEADING = re.compile(r"^#\s+(.*\S)\s*$")
TITLE_PREFIX = re.compile(r"^(?:ADR[\s-]*\d+\s*[—:-]\s*|\d+\.\s+)")

# Likewise two status shapes: `- **Status:** Accepted` and `Status: Accepted`,
# plus a `## Status` section whose value is on a following line.
STATUS_INLINE = re.compile(r"^\s*(?:-\s*)?\*{0,2}Status\*{0,2}\s*:\s*\*{0,2}\s*([A-Za-z]+)", re.M)
STATUS_SECTION = re.compile(r"^#{1,3}\s*Status\s*$\n+\s*\*{0,2}([A-Za-z]+)", re.M)

HEADER = """# ADR index

<!-- Generated by scripts/adr-index.py — do not hand-edit.
     Regenerate:  python scripts/adr-index.py generate
     Check:       python scripts/adr-index.py check -->

| ADR | Title | Status |
| --- | ----- | ------ |
"""


def title_of(text: str, stem: str) -> str:
    """First heading with any numbering stripped; the slug if there is none.

    Two records open with `## Status` and carry no title heading at all, which
    is why this falls back rather than failing: the index should list them
    accurately rather than refuse to build.
    """
    for line in text.splitlines():
        match = HEADING.match(line)
        if not match:
            continue
        heading = match.group(1)
        if heading.strip().lower() == "status":
            continue
        return TITLE_PREFIX.sub("", heading).strip()
    return stem


def status_of(text: str) -> str:
    for pattern in (STATUS_INLINE, STATUS_SECTION):
        match = pattern.search(text)
        if match:
            return match.group(1).capitalize()
    return "Unknown"


def records() -> tuple[list[tuple[int, str, str, str, str]], dict[int, list[str]]]:
    """Every ADR as `(number, label, filename, title, status)`, plus duplicates.

    `label` keeps the filename's own digits so `001` stays `001` in the table,
    while `number` is the integer the sort and the duplicate check use. Early
    records are zero-padded to three digits and later ones are not, and the
    index should reflect the filenames rather than renumber them.
    """
    found: list[tuple[int, str, str, str, str]] = []
    by_number: dict[int, list[str]] = {}
    for path in sorted(ADR_DIR.glob("*.md")):
        match = FILENAME.match(path.name)
        if not match:
            continue  # README.md and any non-numbered note
        label = match.group(1)
        number = int(label)
        text = path.read_text(encoding="utf-8", errors="surrogateescape")
        found.append((number, label, path.name, title_of(text, path.stem), status_of(text)))
        by_number.setdefault(number, []).append(path.name)
    found.sort(key=lambda row: row[0])
    return found, {n: f for n, f in by_number.items() if len(f) > 1}


def render(found: list[tuple[int, str, str, str, str]]) -> str:
    rows = "".join(
        f"| [{label}]({filename}) | {title} | {status} |\n"
        for _number, label, filename, title, status in found
    )
    return HEADER + rows


def main() -> int:
    # ADR titles carry em dashes. On a console whose codepage cannot encode
    # them, printing a diff line would raise while reporting the very record it
    # is describing, so unencodable characters are replaced rather than fatal.
    if isinstance(sys.stdout, io.TextIOWrapper):
        sys.stdout.reconfigure(errors="replace")

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=["generate", "check"])
    args = parser.parse_args()

    if not ADR_DIR.is_dir():
        print(f"{ADR_DIR} is not a directory; run from the repository root", file=sys.stderr)
        return 2

    found, duplicates = records()
    rendered = render(found)

    if args.mode == "generate":
        # A duplicate is still written out -- the index should show the truth --
        # but it is reported, because two files claiming one number is a defect
        # whichever way the table is sorted.
        INDEX.write_text(rendered, encoding="utf-8")
        print(f"wrote {INDEX} with {len(found)} records")
        for number, files in sorted(duplicates.items()):
            print(f"::warning::ADR {number} is claimed by {len(files)}: {', '.join(files)}")
        return 0

    problems = 0
    for number, files in sorted(duplicates.items()):
        print(f"::error::ADR {number} is claimed by {len(files)} files: {', '.join(files)}")
        problems += 1

    current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
    if current != rendered:
        print(f"::error::{INDEX} does not match the ADR files")
        expected = rendered.splitlines()
        actual = current.splitlines()
        for line in range(max(len(expected), len(actual))):
            want = expected[line] if line < len(expected) else "<missing>"
            have = actual[line] if line < len(actual) else "<missing>"
            if want != have:
                print(f"  line {line + 1}:\n    committed: {have}\n    expected:  {want}")
                problems += 1
                if problems > 10:
                    print("  ... further differences not listed")
                    break

    if problems:
        print("\nRegenerate with: python scripts/adr-index.py generate")
        return 1

    print(f"ADR index matches {len(found)} records; no duplicate numbers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
