//! Harmonic Generation: Fubini Series and Tissue Harmonic Imaging
//!
//! # Theory
//!
//! ## Fubini Harmonic Series
//!
//! For a monochromatic sinusoidal source p(0, τ) = P₀ sin(ωτ) propagating in a
//! thermoviscous medium, the nth harmonic amplitude at axial distance z is:
//!
//! ```text
//! |Pₙ(z)| = P₀ × Bₙ(σ) × exp(−α(n·f₀) · z)
//! ```
//!
//! where Bₙ(σ) = (2/(nσ)) Jₙ(nσ) for σ < 1 is the Fubini coefficient (Aanonsen
//! et al. 1984, eq. 6), σ = z/z_shock, and the exp(−α·z) factor is the
//! independent thermoviscous attenuation operator.
//!
//! ## Tissue Harmonic Imaging (THI) Efficiency
//!
//! THI exploits the second harmonic (2f₀) generated by nonlinear propagation.
//! Including pump depletion and differential attenuation, the harmonic accumulation
//! at focal depth F is proportional to:
//!
//! ```text
//! R(F) = F × exp(−κ F),  κ = α(f₀) + α(2f₀)
//! ```
//!
//! The maximum occurs at F_opt = 1/κ, yielding the normalised metric:
//!
//! ```text
//! η(F) = e × κ × F × exp(−κ F)   ∈ (0, 1]
//! ```
//!
//! ## References
//! - Aanonsen SI, Barkve T, Tjøtta JN, Tjøtta S (1984). J. Acoust. Soc. Am. 75(3),
//!   749–768. DOI:10.1121/1.390585
//! - Blackstock DT (1966). J. Acoust. Soc. Am. 39(6), 1019–1026.
//! - Hamilton MF, Blackstock DT (1998). Nonlinear Acoustics. Academic Press. §4.3, §11.
//! - Duck FA (1990). Physical Properties of Tissue. Academic Press.
//! - Church CC (1995). J. Acoust. Soc. Am. 97(3), 1510–1521. DOI:10.1121/1.412131

mod amplitude;
mod contrast;
mod tissue;

#[cfg(test)]
mod tests;

pub use amplitude::{nth_harmonic_amplitude, second_harmonic_amplitude};
pub use contrast::contrast_harmonic_response;
pub use tissue::{optimal_harmonic_frequency, tissue_harmonic_efficiency};
