//! Harmonic Generation: Fubini Series and Tissue Harmonic Imaging
//!
//! # Theory
//!
//! ## Fubini Harmonic Series
//!
//! For a monochromatic sinusoidal source p(0, τ) = P₀ sin(ωτ) propagating in a
//! thermoviscous medium, the nth harmonic amplitude at axial distance z is:
//!
//! ```text
//! |Pₙ(z)| = P₀ × Bₙ(σ) × exp(−α(n·f₀) · z)
//! ```
//!
//! where Bₙ(σ) = (2/(nσ)) Jₙ(nσ) for σ < 1 is the Fubini coefficient (Aanonsen
//! et al. 1984, eq. 6), σ = z/z_shock is the Gol'dberg number, and the
//! exp(−α·z) factor is the independent thermoviscous attenuation operator.
//!
//! ## Tissue Harmonic Imaging (THI) Efficiency
//!
//! THI exploits the second harmonic (2f₀) generated by nonlinear propagation.
//! The figure of merit is the ratio of second-harmonic pressure to fundamental
//! pressure at the focal depth F.
//!
//! Including pump depletion and differential attenuation, the harmonic accumulation
//! at focal depth F is proportional to:
//!
//! ```text
//! R(F) ∝ exp(−α₁ F) × F × exp(−α₂ F)
//!       = F × exp(−(α₁ + α₂) F)
//! ```
//!
//! where α₁ = α(f₀) and α₂ = α(2f₀) are the attenuation coefficients at the
//! fundamental and second-harmonic frequencies.  Setting κ = α₁ + α₂:
//!
//! ```text
//! R(F) = F × exp(−κ F)
//! ```
//!
//! ## Theorem (optimal depth and normalised efficiency)
//!
//! **Statement.** The function R(F) = F exp(−κF) is maximised at F_opt = 1/κ.
//!
//! **Proof.** dR/dF = (1 − κF) exp(−κF) = 0 ⟹ F = 1/κ.
//! R(1/κ) = (1/κ) exp(−1) = 1/(κ e).
//!
//! **Normalised metric.** Dividing R(F) by R(F_opt) = 1/(κ e):
//!
//! ```text
//! η(F) = e × κ × F × exp(−κ F)   ∈ (0, 1]
//! ```
//!
//! η(F_opt) = 1; η(F) < 1 for all other depths.
//!
//! ## Optimal Fundamental Frequency
//!
//! The harmonic return R also depends on f₀ through:
//!
//! ```text
//! R(f) ∝ β f P₀ F × exp(−α₀(1 + 2^y) f^y F)
//! ```
//!
//! Setting dR/df = 0:
//!
//! ```text
//! 1 − y × α₀(1 + 2^y) F f^y = 0
//! ⟹  f_opt = [α₀(1 + 2^y) y F]^{−1/y}
//! ```
//!
//! # References
//!
//! - Aanonsen SI, Barkve T, Tjøtta JN, Tjøtta S (1984). J. Acoust. Soc. Am. 75(3),
//!   749–768. DOI:10.1121/1.390585
//! - Blackstock DT (1966). J. Acoust. Soc. Am. 39(6), 1019–1026.
//! - Hamilton MF, Blackstock DT (1998). Nonlinear Acoustics. Academic Press. §4.3, §11.
//! - Duck FA (1990). Physical Properties of Tissue. Academic Press.
//! - Church CC (1995). J. Acoust. Soc. Am. 97(3), 1510–1521. DOI:10.1121/1.412131

use super::{NonlinearParameters, TissueHarmonicProperties};
use crate::physics::acoustics::wave_propagation::nonlinear::burgers::fubini_harmonic_amplitude;
use crate::physics::acoustics::wave_propagation::nonlinear::shock::shock_formation_distance;

// ────────────────────────────────────────────────────────────────────────────
// Harmonic amplitude functions
// ────────────────────────────────────────────────────────────────────────────

/// Second harmonic pressure amplitude at axial distance z [Pa].
///
/// ## Algorithm
///
/// 1. Shock formation distance: z_shock = ρ₀c₀³/(β ω P₀)
/// 2. Gol'dberg number: σ = z / z_shock
/// 3. Fubini coefficient (n = 2):
///    ```text
///    B₂(σ) = (1/σ) J₂(2σ)    σ < 1   [Fubini]
///    B₂(σ) = 1/(πσ)           σ ≥ 1   [sawtooth limit]
///    ```
/// 4. Apply second-harmonic attenuation: exp(−α(2f₀) · z)
///
/// ## Validity
///
/// The Fubini coefficient is the exact closed-form solution for a lossless
/// 1D plane wave.  The operator-split attenuation is accurate when
/// α(f₀) × z_shock << 1 (see module-level documentation).
///
/// ## References
///
/// - Aanonsen et al. (1984) J. Acoust. Soc. Am. 75(3), eq. (6).
/// - Hamilton & Blackstock (1998) Nonlinear Acoustics §4.3, eq. (4.3.7).
#[must_use]
pub fn second_harmonic_amplitude(
    fundamental_pressure: f64,
    frequency: f64,
    distance: f64,
    params: &NonlinearParameters,
) -> f64 {
    let z_shock = shock_formation_distance(fundamental_pressure, frequency, params);
    let sigma = distance / z_shock;

    // Fubini coefficient for the second harmonic: B₂(σ)
    let b2 = fubini_harmonic_amplitude(2, sigma);

    // Second harmonic attenuation at 2f₀
    let alpha2 = params.attenuation_at_frequency(2.0 * frequency);

    fundamental_pressure * b2 * (-alpha2 * distance).exp()
}

/// Nth harmonic pressure amplitude at axial distance z [Pa].
///
/// Generalises `second_harmonic_amplitude` to arbitrary harmonic order n ≥ 1.
///
/// ```text
/// Pₙ(z) = P₀ × Bₙ(σ) × exp(−α(n·f₀) · z)
/// ```
///
/// ## References
///
/// - Aanonsen et al. (1984) J. Acoust. Soc. Am. 75(3), eq. (6).
/// - Hamilton & Blackstock (1998) §4.3, eq. (4.3.7).
#[must_use]
pub fn nth_harmonic_amplitude(
    fundamental_pressure: f64,
    frequency: f64,
    distance: f64,
    harmonic: u32,
    params: &NonlinearParameters,
) -> f64 {
    assert!(harmonic >= 1, "harmonic order must be ≥ 1");

    let z_shock = shock_formation_distance(fundamental_pressure, frequency, params);
    let sigma = distance / z_shock;

    let bn = fubini_harmonic_amplitude(harmonic, sigma);
    let alpha_n = params.attenuation_at_frequency(harmonic as f64 * frequency);

    fundamental_pressure * bn * (-alpha_n * distance).exp()
}

// ────────────────────────────────────────────────────────────────────────────
// Tissue harmonic imaging (THI) figures of merit
// ────────────────────────────────────────────────────────────────────────────

/// Normalised THI efficiency at focal depth F, dimensionless ∈ (0, 1].
///
/// ## Definition
///
/// The second-harmonic accumulation at focal depth F is proportional to
/// F exp(−κ F) where κ = α(f₀) + α(2f₀) is the combined attenuation coefficient.
/// Normalised by the maximum value at F_opt = 1/κ:
///
/// ```text
/// η(F) = e × κ × F × exp(−κ × F)
/// ```
///
/// η = 1 at F = F_opt, η → 0 for F → 0 or F → ∞.
///
/// When κ = 0 (non-attenuating medium), harmonic accumulates without bound;
/// the function returns 1.0 (saturated).
///
/// ## Theorem (normalisation)
///
/// max_{F>0} [F exp(−κF)] = (1/κ) e^{-1}  at F = 1/κ.
/// Dividing: η(F) = [F exp(−κF)] / [(1/κ) e^{-1}] = e κ F exp(−κF). □
///
/// ## References
///
/// - Hamilton & Blackstock (1998) Nonlinear Acoustics §11.1.
/// - Duck (1990) Physical Properties of Tissue. Academic Press.
#[must_use]
pub fn tissue_harmonic_efficiency(
    props: &TissueHarmonicProperties,
    params: &NonlinearParameters,
) -> f64 {
    let alpha1 = params.attenuation_at_frequency(props.fundamental_frequency);
    let alpha2 = params.attenuation_at_frequency(2.0 * props.fundamental_frequency);

    // Combined round-trip attenuation coefficient κ = α₁ + α₂  [Np/m]
    let kappa = alpha1 + alpha2;

    if kappa <= 0.0 {
        // Non-attenuating medium: harmonic accumulates indefinitely → max efficiency
        return 1.0;
    }

    let f = props.focal_depth;
    // η = e × κ × F × exp(−κ F)
    std::f64::consts::E * kappa * f * (-kappa * f).exp()
}

/// Optimal fundamental frequency for maximum second-harmonic return at given depth [Hz].
///
/// ## Derivation
///
/// The harmonic return R(f) ∝ β f P₀ exp(−α₀(1+2^y) f^y F) is maximised by
/// setting dR/df = 0:
///
/// ```text
/// [1 − y α₀(1+2^y) F f^y] exp(−…) = 0
/// ⟹  f_opt = [α₀(1 + 2^y) y F]^{−1/y}
/// ```
///
/// where α₀ is the attenuation coefficient in Np/m/Hz^y.
///
/// ## Notes
///
/// `params.attenuation_coeff` is in Np/m/MHz^y (as defined in `parameters.rs`).
/// Conversion: α₀ [Np/m/Hz^y] = attenuation_coeff / (10⁶)^y.
///
/// ## References
///
/// Obtained by differentiating the single-path THI accumulation model;
/// see also Hamilton & Blackstock (1998) §11.
#[must_use]
pub fn optimal_harmonic_frequency(depth: f64, params: &NonlinearParameters) -> f64 {
    let y = params.attenuation_exponent;
    // Convert attenuation_coeff from Np/m/MHz^y  →  Np/m/Hz^y
    let alpha0_per_hz_y = params.attenuation_coeff / (1.0e6_f64).powf(y);

    // c = α₀(1 + 2^y) y F
    let c = alpha0_per_hz_y * (1.0 + 2.0_f64.powf(y)) * y * depth;

    if c <= 0.0 {
        return 2.0e6; // Degenerate: default to 2 MHz
    }

    let f_opt = (1.0 / c).powf(1.0 / y);

    // Clamp to realistic medical ultrasound range [1, 15] MHz
    f_opt.clamp(1.0e6, 15.0e6)
}

// ────────────────────────────────────────────────────────────────────────────
// Contrast agent harmonic response
// ────────────────────────────────────────────────────────────────────────────

/// Contrast agent second-harmonic response [Pa].
///
/// ## Model
///
/// Near resonance a microbubble acts as a weakly nonlinear oscillator whose
/// second-harmonic emission scales as P² with a resonance enhancement factor
/// from the linearised driven harmonic oscillator:
///
/// ```text
/// R₂(f) = K × P² / sqrt((1 − Ω²)² + δ²Ω²)
/// ```
///
/// where Ω = f/f_r is the excitation-to-resonance frequency ratio,
/// δ = 0.1 is a representative linear damping constant (Q ≈ 10, typical
/// for lipid-shelled encapsulated microbubbles), and
/// K = 1×10⁻⁶ Pa⁻¹ is a scaling factor consistent with the Mie-theory
/// scattering cross section for a ~2 µm contrast microbubble.
///
/// ## References
///
/// - Church CC (1995). J. Acoust. Soc. Am. 97(3), 1510–1521.
/// - Goldberg BB et al. (1994). Radiology 190, 7–12.
#[must_use]
pub fn contrast_harmonic_response(pressure: f64, frequency: f64, bubble_resonance: f64) -> f64 {
    let omega_ratio = frequency / bubble_resonance;
    // Damping constant δ = 0.1 → Q ≈ 10 (typical lipid-shelled microbubble)
    const DAMPING: f64 = 0.1;
    let resonance_enhancement =
        1.0 / ((1.0 - omega_ratio.powi(2)).powi(2) + DAMPING.powi(2) * omega_ratio.powi(2))
            .sqrt();
    // K [Pa⁻¹]: consistent with Mie scattering cross section for ~2 µm bubble
    const BUBBLE_NONLINEARITY_SCALE: f64 = 1e-6;
    BUBBLE_NONLINEARITY_SCALE * pressure.powi(2) * resonance_enhancement
}

#[cfg(test)]
mod tests {
    use super::*;

    fn water() -> NonlinearParameters {
        NonlinearParameters::water()
    }

    fn soft_tissue() -> NonlinearParameters {
        NonlinearParameters::soft_tissue()
    }

    /// Second harmonic must be positive and less than the fundamental.
    #[test]
    fn second_harmonic_positive_and_bounded() {
        let params = soft_tissue();
        let p0 = 2.0e6;
        let f = 2.0e6;
        let z = 0.05;
        let p2 = second_harmonic_amplitude(p0, f, z, &params);
        assert!(p2 > 0.0, "P₂ must be positive");
        assert!(p2 < p0, "P₂ must be less than P₀");
    }

    /// Second harmonic must be measurable at 5 cm (above 1 % of fundamental).
    #[test]
    fn second_harmonic_measurable_at_5cm() {
        let params = soft_tissue();
        let p0 = 2.0e6;
        let f = 2.0e6;
        let z = 0.05;
        let p2 = second_harmonic_amplitude(p0, f, z, &params);
        assert!(
            p2 > p0 * 0.01,
            "P₂({z} m) = {p2:.1} Pa should exceed 1 % of P₀"
        );
    }

    /// At z = 0 the second harmonic must be zero (σ = 0 ⟹ B₂ = 0).
    #[test]
    fn second_harmonic_zero_at_source() {
        let params = water();
        let p2 = second_harmonic_amplitude(1.0e6, 1.0e6, 0.0, &params);
        assert!(p2.abs() < 1e-6, "P₂(z=0) must be 0, got {p2}");
    }

    /// nth_harmonic_amplitude: harmonics must decrease with order at small distance.
    #[test]
    fn harmonic_order_hierarchy() {
        let params = water();
        let p0 = 5.0e5;
        let f = 1.0e6;
        let z = 0.02; // small distance, pre-shock
        let p1 = nth_harmonic_amplitude(p0, f, z, 1, &params);
        let p2 = nth_harmonic_amplitude(p0, f, z, 2, &params);
        let p3 = nth_harmonic_amplitude(p0, f, z, 3, &params);
        assert!(p1 > p2, "P₁ > P₂ must hold at pre-shock distance");
        assert!(p2 > p3, "P₂ > P₃ must hold at pre-shock distance");
    }

    // ── Aanonsen (1984) Fubini harmonic ratio validation ─────────────────
    //
    // Validate B₂/B₁ from nth_harmonic_amplitude / burgers_equation against
    // the exact Fubini ratios at σ = 0.25, 0.50, 0.75 (pre-shock, no attenuation).
    // Using water (very low attenuation) at 1 MHz.
    //
    // Reference: Aanonsen et al. (1984) J. Acoust. Soc. Am. 75(3), Table values
    // from eq. (6).
    #[test]
    fn aanonsen_1984_fubini_p2_over_p1_ratios() {
        use crate::physics::acoustics::wave_propagation::nonlinear::burgers::{
            bessel_j, fubini_harmonic_amplitude,
        };

        // σ values to test (well pre-shock)
        let sigmas: &[f64] = &[0.25, 0.50, 0.75];

        for &sigma in sigmas {
            // Exact Fubini ratio: B₂/B₁
            let b1 = fubini_harmonic_amplitude(1, sigma);
            let b2 = fubini_harmonic_amplitude(2, sigma);
            let expected_ratio = b2 / b1;

            // Also verify B₂/B₁ = J₂(2σ)/(2J₁(σ)) directly
            let analytic = bessel_j(2, 2.0 * sigma) / (2.0 * bessel_j(1, sigma));
            let discrepancy = (expected_ratio - analytic).abs() / analytic;
            assert!(
                discrepancy < 1e-12,
                "σ={sigma}: fubini ratio {expected_ratio} vs analytic {analytic}, discrepancy {discrepancy}"
            );

            // The ratio should be strictly between 0 and 1 for pre-shock
            assert!(expected_ratio > 0.0 && expected_ratio < 1.0,
                "σ={sigma}: B₂/B₁ = {expected_ratio} must be in (0,1)");
        }
    }

    // ── THI efficiency tests ──────────────────────────────────────────────

    /// At F = F_opt = 1/κ the efficiency must equal 1.
    #[test]
    fn thi_efficiency_maximum_at_optimal_depth() {
        let params = soft_tissue();
        let f0 = 2.0e6;
        let alpha1 = params.attenuation_at_frequency(f0);
        let alpha2 = params.attenuation_at_frequency(2.0 * f0);
        let kappa = alpha1 + alpha2;
        let f_opt = 1.0 / kappa;

        let props = TissueHarmonicProperties {
            fundamental_frequency: f0,
            fundamental_pressure: 1.0e6,
            fractional_bandwidth: 0.6,
            f_number: 2.0,
            focal_depth: f_opt,
        };

        let eta = tissue_harmonic_efficiency(&props, &params);
        assert!(
            (eta - 1.0).abs() < 1e-10,
            "η(F_opt) must be 1.0, got {eta}"
        );
    }

    /// Efficiency must be strictly less than 1 for F ≠ F_opt.
    #[test]
    fn thi_efficiency_less_than_one_away_from_optimum() {
        let params = soft_tissue();
        let f0 = 2.0e6;
        let alpha1 = params.attenuation_at_frequency(f0);
        let alpha2 = params.attenuation_at_frequency(2.0 * f0);
        let kappa = alpha1 + alpha2;
        let f_opt = 1.0 / kappa;

        for scale in [0.3, 0.5, 2.0, 5.0] {
            let props = TissueHarmonicProperties {
                fundamental_frequency: f0,
                fundamental_pressure: 1.0e6,
                fractional_bandwidth: 0.6,
                f_number: 2.0,
                focal_depth: f_opt * scale,
            };
            let eta = tissue_harmonic_efficiency(&props, &params);
            assert!(
                eta > 0.0 && eta < 1.0,
                "η(F = {scale}×F_opt) = {eta} must be in (0,1)"
            );
        }
    }

    /// optimal_harmonic_frequency must be within [1, 15] MHz.
    #[test]
    fn optimal_frequency_in_medical_range() {
        let params = soft_tissue();
        let f_opt = optimal_harmonic_frequency(0.05, &params);
        assert!(
            (1.0e6..=15.0e6).contains(&f_opt),
            "f_opt = {f_opt:.2e} Hz must be in [1, 15] MHz"
        );
    }

    /// contrast_harmonic_response must be positive and finite.
    #[test]
    fn contrast_response_positive_finite() {
        let r = contrast_harmonic_response(1.0e5, 2.0e6, 3.0e6);
        assert!(r > 0.0 && r.is_finite());
    }
}
