//! Parametric Acoustic Arrays
//!
//! Models the nonlinear mixing of two co-propagating primary tones to generate
//! sum and difference frequencies (parametric array / virtual end-fire array).
//!
//! ## Physical Mechanism
//!
//! When two finite-amplitude plane waves at frequencies f₁ and f₂ propagate
//! through a nonlinear medium, quadratic pressure self-interaction drives the
//! generation of new spectral components at f₁ ± f₂ and their harmonics.  The
//! cumulative growth of the difference-frequency component (DFC) f_d = |f₁−f₂|
//! over the primary absorption length ℓ = 1/(2α_T) acts as an end-fire
//! virtual transducer of effective aperture ℓ, giving the DFC a far-field
//! beam width proportional to f_d/f₁ — far narrower than any practical
//! transducer at f_d.
//!
//! ## Theorem (Westervelt Far-Field DFC Amplitude)
//!
//! **Statement.** In the far field (R >> ℓ = 1/(2α_T)), the on-axis DFC
//! pressure generated by two co-propagating plane waves of amplitudes P₁, P₂
//! is (Westervelt 1963, eq. 25):
//!
//! ```text
//! P_d(R) = (β ω_d² P₁ P₂) / (8π ρ₀ c₀⁴ α_T R)
//! ```
//!
//! where β = 1 + B/(2A) is the nonlinearity coefficient, ω_d = 2πf_d,
//! and α_T is the total spatial attenuation of the primary waves [Np/m].
//!
//! **Derivation sketch.** Model the primary interaction as a volume distribution
//! of DFC sources q_d = -(β/ρ₀c₀⁴) P₁P₂ ω_d² cos(ω_d τ) along the propagation
//! axis.  Each source element at z emits a spherical wave.  Integration over
//! the source column from z=0 to ∞, accounting for primary attenuation
//! exp(-2α_T z) and far-field phase accumulation exp(-ik_d z), yields the
//! Westervelt formula above in the limit k_d R >> 1.
//!
//! **Validity conditions:**
//! - Far field: R >> ℓ (absorption length) and R >> k_d⁻¹
//! - Plane-wave primaries: collimated beams of length >> ℓ
//! - Weakly nonlinear: p₁/p₂ << ρ₀c₀² (no shock)
//! - f_d << f₁, f₂ (parametric approximation, |f₁−f₂| << f₁)
//!
//! ## Theorem (Sum Frequency Attenuation)
//!
//! The sum frequency f_s = f₁ + f₂ >> f₁, f₂ so its absorption α_s ∝ f_s^y
//! (with y ≈ 1.1–2.0 for biological tissue) far exceeds the primary absorption.
//! The surviving amplitude at distance R therefore decays as:
//!
//! ```text
//! P_s(R) ∝ R · exp(−α_s R)
//! ```
//!
//! For tissue at 1 MHz primaries and 0.1 MHz DFC, α_s/α_d ≈ 20–200, so sum
//! frequency components vanish within a few millimetres.
//!
//! ## References
//!
//! - Westervelt P.J. (1963). "Parametric acoustic array." J. Acoust. Soc. Am.
//!   35(4), 535–537. DOI: 10.1121/1.1918525
//! - Berktay H.O. (1965). "Possible exploitation of nonlinear acoustics in
//!   underwater transmitting applications." J. Sound Vib. 2(4), 435–461.
//! - Hamilton M.F., Blackstock D.T. (1998). *Nonlinear Acoustics*.
//!   Academic Press, §5 (parametric arrays).

use super::NonlinearParameters;
use std::f64::consts::PI;

/// Calculates the amplitude of the difference frequency (parametric array)
///
/// Mixing f1 and f2 creates f_diff = |f1 - f2|.
/// The virtual array created by nonlinear interaction allows a highly
/// directional low-frequency beam from a small transducer.
///
/// # Mathematical Model
/// Westervelt's solution for the difference frequency pressure on axis:
/// ```text
/// P_diff(R) = (W * β * f_diff²) / (2 * ρ₀ * c₀⁴ * R * α_T)
/// ```
/// Where:
/// - W: Primary acoustical power
/// - f_diff: Difference frequency
/// - α_T: Total attenuation of primaries
#[must_use]
pub fn difference_frequency_amplitude(
    p1: f64,
    p2: f64,
    f1: f64,
    f2: f64,
    distance: f64,
    params: &NonlinearParameters,
) -> f64 {
    let f_diff = (f1 - f2).abs();
    let omega_diff = 2.0 * PI * f_diff;

    // Need an estimate for primary attenuation (Np/m)
    // Assume f1 and f2 are close, take average attenuation
    let f_avg = (f1 + f2) / 2.0;
    let alpha_t = params.attenuation_at_frequency(f_avg);

    let rho_0 = params.density;
    let c_0 = params.sound_speed;
    let beta = params.beta;

    // Far-field DFC amplitude: Westervelt (1963) eq. 25
    // P_d(R) = (β ω_d² P₁ P₂) / (8π ρ₀ c₀⁴ α_T R)
    let p_diff = (p1 * p2 * beta * omega_diff.powi(2))
        / (8.0 * PI * rho_0 * c_0.powi(4) * distance * alpha_t);

    // Self-demodulation limits actual performance
    let self_demod = self_demodulation(p1.max(p2), f_avg, distance, params);

    // Real parametric arrays are often bounded by self-demodulation
    p_diff.min(self_demod * 2.0)
}

/// Calculates the amplitude of the sum frequency
///
/// Sum frequency f_sum = f1 + f2 is highly attenuated since
/// absorption scales with frequency.
#[must_use]
pub fn sum_frequency_amplitude(
    p1: f64,
    p2: f64,
    f1: f64,
    f2: f64,
    distance: f64,
    params: &NonlinearParameters,
) -> f64 {
    let f_sum = f1 + f2;
    let omega_sum = 2.0 * PI * f_sum;

    let rho_0 = params.density;
    let c_0 = params.sound_speed;

    // Fundamental growth factor (similar to second harmonic)
    let coefficient = params.beta * omega_sum / (2.0 * rho_0 * c_0.powi(3));

    // Linear growth estimate (ignoring severe attenuation for a moment)
    let p_sum_raw = coefficient * p1 * p2 * distance;

    // Attenuation of the sum frequency determines survival
    let alpha_sum = params.attenuation_at_frequency(f_sum);
    let survival = (-alpha_sum * distance).exp();

    p_sum_raw * survival
}

/// Estimates self-demodulation (generation of LF envelope)
///
/// A pulsed wave effectively acts as a primary pair, producing low
/// frequencies matching its envelope due to parametric interaction.
#[must_use]
pub fn self_demodulation(
    pulse_pressure: f64,
    _center_freq: f64,
    distance: f64,
    params: &NonlinearParameters,
) -> f64 {
    // Westervelt / Berktay far-field formula (simplified bounding)

    (params.beta * pulse_pressure.powi(2))
        / (16.0 * params.density * params.sound_speed.powi(2) * distance)
}
